### ISSUE TITLE
Show modified flag & prompt on close

### ISSUE THREAD

**Issue by bambu** [rogual/neovim-dot-app#103]
I would like to make a few suggestions for working with windows. 

1. `Cmd-N` opens a new window. `Cmd-W`  only closes a tab and not the window. 

     In terminals and browsers `Cmd-W` will close the current tab and when there are no more tabs, close the only open window.

2. Closing a window by clicking on the red close button (or `Cmd-Q`/`Cmd-W`), should send an rpc message to see if any of the open buffers need saving and then prompt user to save/cancel accordingly.

**Comment by rogual** [comment]
Agreed on both points. We should also get that little dot in the close button when there are unsaved changes.

**Comment by bambu** [comment]
For the dot on the close button, I have an implementation that will do it by setting: `autocmd TextChanged,BufWritePost,InsertLeave * call rpcnotify(ChannelID, "neovim.app.bufchanged", &modified)` 

Looking at the window.mm code I noticed the comment 
```cpp
/* There must be a better way of finding out when the current buffer
   has changed? Until we figure one out, update title every redraw. */
```

Both setting the button and setting the title can be resolved by handling `set_title` that is in `update_o`. What is printed out to the terminal currently is `?? ["set_title", ["[No Name] + - NVIM"]]`. The "+" being that it has been edited. This can be handled either 

a) Within the redraw code and pass the window reference to it 

b) Handle set_title, and any other messages that don't need redraw,  outside of the redraw class and pass the other messages to redraw. 

Thoughts? What is your preference?

**Comment by rogual** [comment]
I don't love the idea of parsing VIM's title string, especially since it is configurable with `set titlestring`. It might be the best way, though.

**Comment by bambu** [comment]
@rogual It doesn't have to be parsed. An `autocmd` can send an rpc message saying that the buffer is dirty. 

I do have a question about that though. Are there any plans for Neovim.app to ever connect to an nvim server instead of launching its own?  If there are, I noticed that all of the `rpcnotify()` calls  assume channel id 1. This is the correct channel id if we are the only one connecting to nvim but if there are other clients, any rpc messages to channel 1 will go to a different client.

**Comment by rogual** [comment]
> @rogual It doesn't have to be parsed. An autocmd can send an rpc message saying that the buffer is dirty.

Oh, good idea. Sorry, didn't read your original comment properly. Let's do this.

> I do have a question about that though. Are there any plans for Neovim.app to ever connect to an nvim server instead of launching its own?

I'm not against it but there would be a few decisions to make. It would be useful to have as it would make it a bit easier to run nvim under a debugger.

Re. the messages, yeah, that would need changing if we wanted the nvim process to use our nvimrc. I'm not sure if we would, though?

**Comment by bambu** [comment]
I have the modified flag part done. 

@rogual 
What are your thoughts on keeping track of data such as the current buffers, tabs, windows etc.? I am considering adding buffer tracking to `vim.h` to help with the prompting when closing the window when there are dirty buffers. this way there is less async communication as the buffer metadata will already be there.

**Comment by rogual** [comment]
At this point I would err on the side of not doing that, unless it's demonstrably causing performance problems. This is just because
1. Increases in code complexity should only happen when necessary, and
2. I don't trust Vim to always notify us when changing its internal state

**Comment by bambu** [comment]
#148 was merged
