### ISSUE TITLE
Passing command line options to neovim-dot-app

### ISSUE THREAD

**Issue by dsanson** [rogual/neovim-dot-app#108]
I would be nice to have the full power of the command line nvim when launching Neovim.app from a terminal, e.g.,

```
/Applications/Neovim.app/Contents/MacOS/Neovim +10 file.txt
```

I know many OSX apps allow this (Macvim is one; Firefox is another) but I don't know what implementing this entails.

Among other things, this would allow us to adapt the techniques used by the `mvim` script instead of relying on OS X's `open` command (see Issue #97). So then we could have a `neovim` script that mimics the behavior of `mvim` or `gvim`.

**Comment by rogual** [comment]
Yeah, we definitely need this. Should be a relatively easy change.

**Comment by bambu** [comment]
@rogual,  ab0f83b0db265e0cb3b79a0342223a6dc673c75c should be a start to what you want.

I created a modified mvim to launch either nvim or Neovim and it works fine. It  is not currently in the referenced commit.  Calling Neovim with nvim arguments also works as shown in @dsanson's example also works. 

In the process I also noticed that `openFile` gets called a few times so i removed that code. 

Let me know if it works for you and i'll do make a pull request

**Comment by rogual** [comment]
> @rogual, ab0f83b should be a start to what you want.

Looks good!

**Comment by bambu** [comment]
Pull request #111 should provide this functionality. 

I'll look at how to make a script install with the SConstruct build system. 

@rogual any preference on the name of the script?
* nnvim
* neovim
* n.a
* nvim.app
* something else?

**Comment by rogual** [comment]
Fixed with https://github.com/rogual/neovim-dot-app/pull/111

@bambu I'm not 100% convinced we need to include a script. Can discuss in a separate issue if you like.
