### ISSUE TITLE
Minor issue: repo named .app

### ISSUE THREAD

**Issue by jdavis** [rogual/neovim-dot-app#11]
This is more of just a nuisance, but by naming the repo `.app` when doing a default `git clone` without providing an alternative name for the folder or else running `mv` on it, OS X by default will think it is an app. If it was `neovim-app` it might work better.

**Comment by rogual** [comment]
Huh, you're right. You'd think they'd at least check for an Info.plist or something. OK, renamed back to neovim-dot-app.
