### ISSUE TITLE
Consider changing default working dir

### ISSUE THREAD

**Issue by philplckthun** [rogual/neovim-dot-app#110]
When starting the app the working directory is by default set to root `/`, which is not really useful. Atm I have to set the working directory manually by using `:lcd %:p:h`... It would be nice if an open file/folder dialog opened by default.

Also when I'm opening a file with Neovim the current work dir is still root. Also really annoying.

**Comment by bambu** [comment]
@philplckthun 
I agree that there should be an open file window, and that when selecting a file it should change your working directory. However, I personally would not like it if it opens up automatically on a new window. I often open vim/nvim/vimr and start working from a blank buffer or  use a  get to my vimrc via hotkey. In those cases having an open dialog would get annoying. 

In any case, the default working directory should not be root. It should be the users home directory by default. When Neovim.app is run from command line, the working directory is set correctly. So this is likely an enviroment variable issue. 

I suggest the following:
1. Determine whether Neovim is being run from cmd line. If not, set the initial working directory to ~/
2. Open dialog accessible via Cmd-O
3. Opening a file via dialog sets the working directory to it.
4. Setting to make file dialog display on start

Thoughts?

**Comment by philplckthun** [comment]
Sounds good!

Actually the directory is set correctly if opened from the command line. So that indeed works. I'll look into the standard working directory issue, which sets root instead of the home directory as the default work dir.

**Comment by philplckthun** [comment]
Hmm still not that simple I suppose. A dialog not always sets the working directory. Only initially it should do that. Basically a single window has one vim process and thus one working directory.

Also when the window is opened the arguments shouldn't be opened by using vim's `e` command. They should be directly given as arguments to vim.

The working directory should always be set via the `pwd` command in my opinion and should override vim's "assumptions" for the work dir. (Once per window as said above)

**Comment by rogual** [comment]
It looks like there are two issues here:

1. Do we want to override the default working directory?
2. Do we want an open-file dialog to appear on startup?

For 1., I agree that / isn't too useful as a working dir. How about if we set PWD to ~ using LSEnvironment in Info.plist? 

As for 2., how about if we leave that as something users can do via their .vimrc?

**Comment by philplckthun** [comment]
**Proposal for the quickest fix:**

1. Set the pwd in the LSEnvironment in Info.plist (I'll check this out right now)
2. Add a file/folder open dialog on `Cmd-O`.
3. A new window should open files via passing them as arguments to the vim process instead of opening them through vim's edit command, I believe

I think this already suffices. `set autochdir` is not what in the scope of the issue here, as it always changes the working directory, instead of setting it just once.

**Comment by rogual** [comment]
I was just mentioning `autochdir` in response to @bambu's idea: “Opening a file via dialog sets the working directory to it.”

If I understand you correctly @philplckthun it sounds like your no. 1 would possibly fix this issue, and 2 and 3 would both be nice but won't affect anything to do with the working dir. Have I understood right?

**Comment by philplckthun** [comment]
@rogual Yep

**Comment by bambu** [comment]
@philplckthun,
Your points 1 and 2 are good. I think I agree with 3 but there might be some ambiguity in it due to your original suggestion.

I agree that a file opened by a new window should open through the vim process. If you check my latest PR #111 it removes opening files with :e (because it would cause the file to load about 3 times) and instead passes it through the execve. 

I dont think that upon opening Neovim we should get an open dialog by default as you may want to do things on a fresh buffer.  This could very well be made an option. If we want to open a file via dialog, then use Cmd-O (sort of like in Vimr or MacVim).

In order have an  option in the vimrc like @rogual suggests and still comply with suggestion 3,  we would need to either parse the vimrc first prior to launching nvim or have a separate config that would hold that option.

**Comment by philplckthun** [comment]
@bambu 
I think point 3 would be fixed by your #111. Opening via :e is pretty buggy, but this should fix it.

**Comment by bambu** [comment]
I added support for the open dialog box. Cmd-O or File/Open allows you to open a new file via GUI. In doing so I realized how limited my original approach to #111 was. Made it more flexible.

**Comment by philplckthun** [comment]
:+1:

**Comment by bambu** [comment]
@philplckthun, did you ever implement the LSEnvironment thing for the working directory? If not, I'll take a stab at it tomorrow

**Comment by philplckthun** [comment]
@bambu No, didn't take a look at that yet. There's also a problem opening files outside of Neovim I think. And draggin them into the Neovim windows

**Comment by bambu** [comment]
Not sure what you mean by opening files outside of Neovim but I am able to drag files into the windows without a problem. 

I tested the following scenarios:
1. Dragging file into window on open
2. Dragging file into window after a file is open
3. Opening a tab and dragging a file into it
4. Opening a new window and dragging a file into it.
5. All of the above on the latest build of nvim

**Comment by bambu** [comment]
I think this issue can be closed. All action items that were originally addressed have been completed.

The recent ones by @philplckthun should be separate issues and have also been addressed in PRs #127 #131

**Comment by philplckthun** [comment]
@rogual @bambu I also mentioned this commit: https://github.com/philplckthun/neovim-dot-app/commit/d336587 in PR #126.

At the time the working directory is static as far as I'm concerned, but wouldn't it make sense to change it per window depending on the file / folder being edited?

**Comment by rogual** [comment]
Do you mean set it once when a new window is opened, or have it track the current file?

**Comment by philplckthun** [comment]
Once when a new window is opened. Just check out the commit. It's basically a single line in the nvimrc

**Comment by rogual** [comment]
I can see why this woulld make sense for some users — perhaps a lot of users — but I'm not sure it should be the default. It would be a very visible departure from standard Vim behaviour.

**Comment by philplckthun** [comment]
Well from a CLI standpoint the working directory is obvious, but from a GUI standpoint that almost always chooses `~`, it's just not a matter about preference.

Consider opening the app normally. The working directory is going to be `~` by default.

Consider opening vim. The working directory is determined by the shell.

But if you're opening files inside vim the working directory is not going to change. Thus the working directory being `~` is in almost all cases useless.

The easiest thing to do here is just somehow determining where a project's root is. The commit I referenced is just the easiest solution. It's for sure imperfect, but a start

**Comment by bambu** [comment]
I have to agree with @rogual as for your solution. Here's my common use case as to why: 

If I open via CLI Neovim.app in a directory that I want to do `:r !ls` (or any other type of command that requires the directory that i am in, then doing a `cd %:p:h` will change my directory. 

I would agree that if you do an OpenWith from finder or File->Open from Neovim.app that it should have the directory be the same as the file that is opened. I believe this is also what happens in Vimr/MacVim

**Comment by philplckthun** [comment]
@bambu Then I guess the best idea would be to change the working directory if something is opened with the Finder or with Open With
