### ISSUE TITLE
Leader keys and some other key sequences not working with showcmd

### ISSUE THREAD

**Issue by rogual** [rogual/neovim-dot-app#112]
**Quick Workaround:** Use https://github.com/neovim/neovim/commit/e1f83d304dc787374ae152bb308599dd024ae2bb until this is sorted.

- User-set keybindings with a prefix key are broken
- Vim receives the leader but doesn't wait for another key.
- When using `[` or `]` or `g` the char appears briefly in lower-right of screen followed by `~@ý`. Not all prefixes do this; `,` shows the unadorned `,` but it still disappears right away.
- Only happens when `set showcmd` is on
- Neovim itself works in terminal still, only API is affected.
- Happens in any Neovim since https://github.com/neovim/neovim/commit/ccdeb91e1206f38773664979bf03694213a2ba80
- Looks like the reference Python client received an update just afterwards: https://github.com/neovim/python-client/commits/master
- Using the Python client, even manually sending the vim_input update as a request (not a notification), the bug does not manifest.
- Swithing Neovim.app to send RPC notifications rather than calls for `vim_input` does not help.
- **It seems text objects are also broken regardless of `showcmd`**

**Comment by rogual** [comment]
This only happens when `set showcmd` is on.

**Comment by rogual** [comment]
Opened this issue with Neovim https://github.com/neovim/neovim/issues/3282

**Comment by bambu** [comment]
Using PR #123  I was able to do the following things that are broken in the current branch.

*Vim receives the leader but doesn't wait for another key.
*When using [ or ] or g the char appears briefly in lower-right of screen followed by ~@ý. Not all prefixes 
*do this; , shows the unadorned , but it still disappears right away.
*Only happens when set showcmd is on
*It seems text objects are also broken regardless of showcmd

Didn't test the others

**Comment by baileyparker** [comment]
On 8b3590a2dd1de2aec2ea89136911716ac29313bc compiled with neovim/neovim@1ba081a6735e74446d5e9e05d0fb0bf9cca31f63, I can reproduce this. Additionally, I can add the following (hopefully helpful information):

While it is true that the g character does appear briefly followed by ~@ý, I've found this doesn't happen with double g's. If you jump to a line with `10gg`, the movement command never fails. Strangely, though, it always fails when I try to `gg` back to the top of the file (but `1gg` still works).

This is with a `.nvimrc` containing only `set showcmd`, so I can't imagine any plugin interference causing this.

I can try compiling #123 to see if it fixes this edge case of the `g` issues.

**Comment by rogual** [comment]
I have merged #123 which seems to fix the issue entirely for me. Can you reproduce on latest master @baileyparker ?

**Comment by rogual** [comment]
OK, I'm closing this. Quick summary:

* Neovim introduced a bug
* Our app triggered this bug as a side-effect of redrawing its titlebar too often
* We changed our app to no longer do this
* Now Neovim seem to have fixed their bug: https://github.com/neovim/neovim/pull/3413

**Comment by baileyparker** [comment]
Apologies for the delay. I can confirm that after compiling & running the HEADs of both `neovim-dot-app` and `neovim`, I can no longer reproduce this issue.

Thanks for addressing this!
