### ISSUE TITLE
NSFontManager delegate has been deprecated in OS X 10.11

### ISSUE THREAD

**Issue by bambu** [rogual/neovim-dot-app#113]
The `delegate` and `setDelegate` properties have been deprecated in OS X 10.11 ([link to api](https://developer.apple.com/library/prerelease/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSFontManager_Class/index.html))

The affected code is in `view.mm` line `37`.
```obj-c
[[NSFontManager sharedFontManager] setDelegate:self];
```

Commenting the line out does not seem to have any effect on the way that fonts are loaded or set. Is this line necessary for versions prior to 10.11? If so, it can be surrounded by:

```obj-c
#ifndef __MAC_10_11
    [[NSFontManager sharedFontManager] setDelegate:self];
#endif
```

Here is the build output when compiling:
```clang
clang++ -o build/view.o -c -std=c++11 -stdlib=libc++ -g -Wno-deprecated-register -Ibuild -Isrc src/view.mm
src/view.mm:37:44: warning: 'setDelegate:' is deprecated: first deprecated in OS X 10.11 - NSFontManager doesn't have any delegate method. This property should not be used.
      [-Wdeprecated-declarations]
        [[NSFontManager sharedFontManager] setDelegate:self];
                                           ^
/System/Library/Frameworks/AppKit.framework/Headers/NSFontManager.h:111:33: note: property 'delegate' is declared deprecated here
@property (nullable, assign) id delegate NS_DEPRECATED_MAC(10_0, 10_11, "NSFontManager doesn't have any delegate method. This property should not be used.");
                                ^
/System/Library/Frameworks/AppKit.framework/Headers/NSFontManager.h:111:33: note: 'setDelegate:' has been explicitly marked deprecated here
1 warning generated.
```

**Comment by philplckthun** [comment]
@bambu Also running El Capitan. Will test this asap, and report back to you

**Comment by philplckthun** [comment]
@bambu Works for me

**Comment by rogual** [comment]
I suspect we can just remove this line altogether. As long as the font panel and `call MacSetFont` still works I'm happy for it to go.

**Comment by gglanzani** [comment]
You can find the video here. Note that after 2s I stop pressing j. This does not happen with Neovim in the terminal but always happened to me with neovim-dot-app

https://www.youtube.com/watch?v=b3zv4n_l8HI&feature=youtube_gdata

As you can see, scrolling is basically fine.

**Comment by philplckthun** [comment]
@gglanzani Did you mean to post that to #109? I guess it's a problem with the key repress rate, because I've not got that enabled. I press j separately all the time. So if you hold it down it's probably spamming the event loop. We should try to add some kind of buffer to that.
