### ISSUE TITLE
Noisy menu calls

### ISSUE THREAD

**Issue by bambu** [rogual/neovim-dot-app#114]
In using the recently added menu items, I notice that whenever they are used the command is displayed in the command line and stays there until an action that updates the line is performed (lose/gain focus, go into command mode, etc..). 

Because this is an gui action, I suggest adding `<silent>` to the `anoremenu` commands in the `nvimrc`. This way if, for example, you open the Show Fonts dialog with `Edit/Show Fonts` you do not have `call ShowFontSelector()` lingering until you cause a refresh.

**Comment by philplckthun** [comment]
+1

**Comment by rogual** [comment]
On the other hand, if you discover a useful command in the menu, it might be useful that Vim shows you the command-line for it.

**Comment by bambu** [comment]
I have grown accustomed to seeing it. So i guess it is not that big of a deal to have it on. Thoughts @philplckthun

**Comment by philplckthun** [comment]
@bambu I don't mind it anymore. Not that disturbing and like @rogual said: This could grow useful for people, who don't want to read the Neovim.app source
