### ISSUE TITLE
Title should be set and only updated when Nvim sends set_title message

### ISSUE THREAD

**Issue by bambu** [rogual/neovim-dot-app#122]
Currently the title is updated every time a redraw occurs. Redraws happen often and as such the title gets set when it shouldn't have to be set.  

Within the `redraw` rpc msg there is an action called `set_title` that specifies the title and is received when the title should be updated. The title should only be updated when this message is received. Likewise, the title should be set to the contents of this message. 

This `set_title` can be seen by running the Neovim binary from terminal (not using open).

**Comment by philplckthun** [comment]
This should probably suffice: https://github.com/philplckthun/neovim-dot-app/commit/3736868

I tried getting a "set_title" rpc event, but didn't have any luck. The `set_title` option just enabled a weird output, but no extra event. A quick Google search also didn't unveil anything new.

**Comment by bambu** [comment]
Sorry I should have clarified. `set_title` is part of redraw. If you launch Neovim.app Mach-o binary from terminal you'll see the `set_title`. It is printed to stdout. It is printed in the `if(!action)` of the redraw method in redraw.mm. I'm not on my computer so can't copy the output. 

In order to handle it, set_title needs to be added to the redraw.gperf file and handled in the doAction withArgc function. 

The only difficulty is that redraw.mm doesn't have an instance of the window so it would somehow need to be passed to it. Either that or parse out  `set_title` as well as any other redraw action that relates to ui from the redraw message and handle it in window.mm

**Comment by philplckthun** [comment]
@bambu Oh, that's awesome! What I was looking for. Thanks for pointing that out. I'll try to get this to work

**Comment by philplckthun** [comment]
@bambu Check out #123. Is that what you meant? I didn't realize how to get the appropriate rpc message or that it even was one. We probably should change the output to be clearer.

**Comment by rogual** [comment]
Yeah, 'ignoring message' would probably be better than '???'

**Comment by bambu** [comment]
* +1 to "Ignoring messages" instead of ?? (though it doesn't bother me to see it as ??)
 
* +1 to Having a debug flag. Only if it can be set at compile time `make DEBUG=1` or something like that. 

* I am not too familiar with `NSLog`. I prefer  `std::cout` because when you do `std;cout << msgpack_obj` it actually prints out the object nicely. Due to unfamiliarity with objective-c I am unsure of how this can be accomplished using `NSLog`.

**Comment by rogual** [comment]
> +1 to Having a debug flag. Only if it can be set at compile time make DEBUG=1 or something like that.

Fine by me.

> I am not too familiar with NSLog. I prefer std::cout because when you do std;cout << msgpack_obj it actually prints out the object nicely. Due to unfamiliarity with objective-c I am unsure of how this can be accomplished using NSLog.

You'd have to use a stringstream and convert to NSString. Extra effort, but NSLog might have advantages I don't know about.
