### ISSUE TITLE
Cursor movement is slow.

### ISSUE THREAD

**Issue by jordwalke** [rogual/neovim-dot-app#124]
I just cloned/built master, and moving the cursor around is very slow. MacVim is much faster.

**Comment by jordwalke** [comment]
Could this have something to do with the fact that my key repeat rate is set to a custom (very fast) rate? MacVim and every other app seem to handle it fine though.

**Comment by philplckthun** [comment]
Likely related to #115

**Comment by rogual** [comment]
Closing in favour of https://github.com/rogual/neovim-dot-app/issues/99
