### ISSUE TITLE
Catch rpc commands that fail

### ISSUE THREAD

**Issue by bambu** [rogual/neovim-dot-app#128]
Calls to vim_command that may result in an error should be checked for error. 

An example is  calling `vim_command` or `vim_command_output` with a command that is not going to be successful. An example of this would be dragging a file into a window when `set nohidden` is on and a file is edited. Doing `:enew` or any sort of file opening in vim will usually output the error
```
E37: No write since last change (add ! to override)
```
This message is passed into the error variable from callback but is often times not checked. The error appears as: 
```
[0, "Vim(edit):E37: No write since last change (add ! to override)"]
```

**Comment by rogual** [comment]
Can you identify where in the codebase we use commands that might fail?

**Comment by bambu** [comment]
In the case of dragging, I think that we should do like VimR/MacVim do and open it in another tab if you either have a file open or are in an unnamed buffer that has been modified. 

Depending on the vim command there is a possibility of failure. I think we should, at the minimum, pass the error back to nvim with `vim_report_error`.  In the case that we can handle the error, handle it ourselves/prevent it and pass on any further errors to `vim_report_error`.

An example of the latter: 
The SavePanel will save. If the file already exists during a save as, with the current save, it will report `E13: File exists (add ! to override)`.  In this case, i can prevent that error by saying `w!` or `sav!` which would make sense because the user agreed to overwrite the file. This fixes this problem. However, if i try to overwrite a file that I dont have write access to I'll get `E212: Can't open file for writing`. This error can be passed on to nvim and it should make sense to the user what is going on. 

I think an alert sheet should be used when the error will not make sense being viewed as reported by `vim_report_error`. IE, if you get the previously mentioned `E37` error when dragging a file, it may not be obvious what is going on if what you see is `No write since last change (add ! to override)`

**Comment by bambu** [comment]
#131 & #129 have been merged. Could not find any other areas where an error would occur that is not displayed to screen.
