### ISSUE TITLE
missing instruction for installing Neovim

### ISSUE THREAD

**Issue by masukomi** [rogual/neovim-dot-app#13]
it says 

    brew install --HEAD neovim

It *should* say

    brew tap neovim/homebrew-neovim
    brew install --HEAD neovim

**Comment by fwalch** [comment]
Best would probably be to just link to https://github.com/neovim/neovim/wiki/Installing-Neovim#os-x--homebrew

**Comment by rogual** [comment]
Fixed with https://github.com/rogual/neovim-dot-app/pull/15
