### ISSUE TITLE
Python3 is not available

### ISSUE THREAD

**Issue by eesdil** [rogual/neovim-dot-app#134]
Even if I put the line in the .nvimrc:
```
    let g:python_host_prog='/usr/local/bin/python3'
```
Neovim.app doesnt recognize python3, so deoplete is not working.
The same thing working fine in the terminal in nvim.

**Comment by bambu** [comment]
Followed instructions on the [deoplete github](https://github.com/Shougo/deoplete.nvim) could not get it to work with the pip3 install of nvim. I did check to make sure that `echo has('python3')` resulted in true.

**Comment by bambu** [comment]
@eesdil ,
Finally got deoplete to work in terminal nvim. There were some conflicting issues with my .nvimrc that i fixed. Deoplete worked out of the box with the latest version of Neovim.app. 

Check that the nvim that you compile Neovim.app to use is the same one that you are running in your terminal and that both return the value of `1` when you run `:echo has('python3')` as deoplete page suggests. 
You build a Neovim.app with a specific version of nvim using:
```
make NVIM=/path/to/nvim
```

In my particular setup, I followed the setup on the github page and it installed a python3 version of nvim to `/usr/local/bin/nvim`. I then built Neovim.app to use that directory (after i got deoplete working in nvim).  

Let me know how it goes for you.

**Comment by eesdil** [comment]
thank you for the help @bambu . And sorry for the false alarm, I had a manual installation of neovim.app and it was called instead of the one from brew...
After removed that it is working fine (except cursor the speed, but thats another topic)

thanks again
