### ISSUE TITLE
The cursor does not desaparace writing 

### ISSUE THREAD

**Issue by tanrax** [rogual/neovim-dot-app#136]

**Comment by bambu** [comment]
No entiendo lo que estas tratando de decir. Tu titulo dice "el cursor no desaparece escribiendo".

**Comment by tanrax** [comment]
Exacto. Que cuando tecleas no desaparece el cursor del ratón.

**Comment by bambu** [comment]
Ahh ya entiendo. Gracias. Debe de estar arreglado en PR #139. Tratalo y dime si funciona. 

No hablo castellano. Mi español es caribeño.
