### ISSUE TITLE
Ignore Caps Lock in OS X

### ISSUE THREAD

**Issue by tanrax** [rogual/neovim-dot-app#138]
But you can write uppercase when you hold the shift key

**Comment by bambu** [comment]
I got out of the habit of using caps lock so I have never noticed that capslock doesn't work. Thanks for discovering this.  :-)

**Comment by tanrax** [comment]
@bambu Thank you for your great work! :)

**Comment by rogual** [comment]
> I got out of the habit of using caps lock so I have never noticed that capslock doesn't work

Same here!
