### ISSUE TITLE
 fatal error: 'msgpack.hpp' file not found

### ISSUE THREAD

**Issue by masukomi** [rogual/neovim-dot-app#14]
after following the instructions to `brew install msgpack` my `msgpack.hpp` is located at `/usr/local/Cellar/msgpack/0.5.9/include/msgpack.hpp`

and yet  when I run `make`

```
$ make
VIM=/usr/local/Cellar/neovim/HEAD/share/nvim NVIM=/usr/local/bin/nvim scons -Q
Install file: "res/Info.plist" as "build/NeoVim.app/Contents/Info.plist"
g++ -o build/client.o -c -std=c++11 -g -Wno-deprecated-register -Ibuild -Isrc src/client.cc
src/client.cc:5:10: fatal error: 'msgpack.hpp' file not found
#include <msgpack.hpp>
         ^
1 error generated.
scons: *** [build/client.o] Error 1
make: *** [all] Error 2
```

my head is at 

    2d30d73 Fixes & changes to build system

**Comment by fwalch** [comment]
Probably won't fix the problem, but your msgpack version seems to be too old. Current version in homebrew is 1.0.1.

**Comment by kiryph** [comment]
Extend the file `SConstruct`:
```diff
 env.Append(
     CCFLAGS=['-std=c++11', '-g', '-Wno-deprecated-register'],
-    CPPPATH=['build'],
+    CPPPATH=['build', '/usr/local/include'],
     LIBS=['msgpack'],
+    LIBPATH=['/usr/local/lib'],
     FRAMEWORKS=['Cocoa']
 )
```

**Comment by rogual** [comment]
That will work, but I wouldn't recommend it as SConstruct is for project-specific paths, and if you change your local copy, you'll get conflicts if anything changes.

Instead, you should add the folders under /usr/local to your own system's paths. IIRC you can do this with

`xcode-select --install`

**Comment by rogual** [comment]
Anyway, I'm closing this since it's a system configuration issue rather than a bug in Neovim.app

**Comment by fedorpashin** [comment]
@rogual it doesn't help, I get this error:

> xcode-select: error: command line tools are already installed, use "Software Update" to install updates

**Comment by davetron5000** [comment]
Same for me.  The suggested change for modifying `SConstruct` also did not work as homebrew installed into `/opt/homebrew/Cellar`.  Adding *that* didn't work either.  Whatever homebrew installed for 6.0.0 of msgpack doesn't have the file `msgpack.hpp` in it anywhere that I can see.

I can't uninstall it because neovim needs it.  Perhaps that's related?
