### ISSUE TITLE
Window title not updated if file saved with new name

### ISSUE THREAD

**Issue by rogual** [rogual/neovim-dot-app#144]
1. Start app
2. `:w ~/a.txt` — Title becomes a.txt
3. `:w ~/b.txt` — Title should become b.txt but doesn't

We have `MacUpdateTitle()` called on `BufWritePost` so this should work — but doesn't. Can anyone reproduce this?

**Comment by bambu** [comment]
That is not a bug. That is the way that vim works. You can open vim/nvim and try it. When a file is already saved any `:w filename` will save the current buffer to that file but it will not update the buffer to have the new name. If you want to update the buffer you have to do `:saveas filename`

**Comment by rogual** [comment]
D'oh.
