### ISSUE TITLE
`xcode-select --install` as part of installation

### ISSUE THREAD

**Issue by sindriava** [rogual/neovim-dot-app#154]
Could we do `xcode-select --install` during installation, to check if the tools are installed? I've spent a few minutes working this out, because I've just updated to El Capitan and had to reinstall them for some reason. Not having them installed just produces a weird error.

If the tools are installed, xcode-select will return 1. If not, a dialog should pop up and xcode-select should block until they're installed. This would ensure the installation doesn't go through until they are installed :smile:

**Comment by sindriava** [comment]
While the README.md page mentions that those tools are required, they can apparently be reset by certain events, which makes this error even more puzzling when it occurs. The solution I found was in #106.

**Comment by rogual** [comment]
You mean during installation via Homebrew? The thing is, I'm pretty sure every Homebrew package needs the command-line developer tools to be installed in order to compile. I mean, `brew doctor` itself will tell you if they aren't there.  I guess we could tell people to run `brew doctor`.

**Comment by sindriava** [comment]
The tools don't only have to be present, but the license needs to be agreed. I'm not sure if homebrew checks that but even if it did, the issue is that neovim-dot-app generates a very confusing error message when this happens.

I haven't experienced this with other projects and this might be a symptom of a deeper issue with either the way this project is built, or how the brew package is configured (maybe a check is omitted?)

Either way, I'm not the first to encounter this issue and probably not the last one, and I don't think that running xcode-select as a part of the build process is a concernable overhead.

**Comment by rogual** [comment]
What error message were you getting?
