### ISSUE TITLE
Cannot open files from nvALT

### ISSUE THREAD

**Issue by johnstephens** [rogual/neovim-dot-app#155]
_I accidentally opened this issue under homebrew-neovim-dot-app, but I'm not sure if that was the right place._

I'm using nvALT version 2.2b (111). The files are plain text with various extensions—mostly .md (Markdown) and .wiki (Vimwiki). When I use nvALT's preferences to set MacVim as my external editor, I can open nvALT files in MacVim with a simple keyboard shortcut, edit the files in MacVim, save and return to nvALT seamlessly.

I can open all the files in both nvALT and in Neovim. But when I set Neovim.app as my external editor for nvALT, I get an error message every time:

> The document "Test.md" could not be opened. Neovim cannot open files in the "Markdown" format.

When I close the error dialog, I see an empty "[No Name]" buffer, and Vim's `pwd` command returns my home directory, not the directory where my nvALT files are stored.

Switching the external editor back to MacVim in nvALT's preferences restores the expected behavior with seamless integration between the two apps, but of course MacVim is not Neovim.

I'd be happy to take any steps you suggest to troubleshoot the issue or provide any further information I can.

**Comment by bambu** [comment]
This is likely related to #146 and PR #127. Once that PR is resolved it should work. :-)

**Comment by johnstephens** [comment]
Thanks! I'll keep an eye on those.

**Comment by rogual** [comment]
This may be fixed now. Please see comment on https://github.com/rogual/neovim-dot-app/issues/146 re. caching though.

**Comment by johnstephens** [comment]
:+1: :bread:
