### ISSUE TITLE
command to open file in Neovim.app

### ISSUE THREAD

**Issue by jbaum98** [rogual/neovim-dot-app#162]
I wrote a tiny script to open a file in Neovim.app instead of terminal neovim:
```sh
#!/bin/sh
open -a Neovim --args $@
```
I think this should be added to the homebrew installation so it will automatically be installed, but I didn't make a pull request because I'm not sure where it goes.

**Comment by rogual** [comment]
Thanks! This feature request has come up before, the only issue being “what do we call the script”. I think it's about time we added this, so I've decided on **gnvim**.

Will update the homebrew formula separately.
