### ISSUE TITLE
El capitan compilation 

### ISSUE THREAD

**Issue by gambledor** [rogual/neovim-dot-app#163]
Compiling from source does not recognize mouse events 
 ```
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
```

**Comment by rogual** [comment]
That's odd — I'm on El Cap and it works for me. Can you try launching with `-u NONE` and make sure it isn't something about your config?

**Comment by gambledor** [comment]
it's been related to the fact that neovim did not have a $HOME/.config/nvim/init.vim file
Once a I've created it all went smooth.

**Comment by gambledor** [comment]
Using the mouse to click on menu voices nothing happens.
For example:
***Quit*** on the menu or ***Cmd-Q*** does nothing.

**Comment by rogual** [comment]
Could you try with latest master? I just committed a fix  (https://github.com/rogual/neovim-dot-app/commit/57f0d8317eaf17b46b37e0487d2a419fa7ea7a03) which should resolve a lot of recent weirdness, maybe including this.

**Comment by gambledor** [comment]
Ok, it has been fixed. :+1:
