### ISSUE TITLE
cannot install neovim.app with home-brew

### ISSUE THREAD

**Issue by njdavis** [rogual/neovim-dot-app#164]
when I try to install neovim.app, I get the following error:

ld: library not found for -lmsgpack 

I have tried to reinstall the xCode command line tools and that did not help.

**Comment by rogual** [comment]
try running `xcode-select --install` and trying again?

**Comment by njdavis** [comment]
it says that: xcode-select: error: command line tools are already installed, use "Software Update" to install updates

there don't seem to be any updates.

**Comment by rogual** [comment]
OK, so either msgpack isn't installed or the compiler isn't seeing it. Try doing:

`ls -l /usr/local/lib/libmsgpack.a`

If the file isn't there, then you need to reinstall msgpack:

`brew uninstall msgpack`
`brew install msgpack`

If it *is* there, something weird is happening.

**Comment by njdavis** [comment]
Thanks. The install worked, however, no I cannot open .cpp or .h files with the application. 

I get the following error: Neovim cannot open files in the "C Header" format.

When I try opening it with neovim in the terminal, it works.

**Comment by rogual** [comment]
How are you trying to open the file?

**Comment by njdavis** [comment]
from finder

**Comment by rogual** [comment]
That's a known issue and should be fixed when https://github.com/rogual/neovim-dot-app/pull/127 gets merged.
