### ISSUE TITLE
Can not open files from shell

### ISSUE THREAD

**Issue by Stiivi** [rogual/neovim-dot-app#17]
When trying to open a file from command using `open -a Neovim FILENAME` i'm getting the following error alter:
`The document “maybe.h” could not be opened. Neovim cannot open files in the “C header code” format.`

![screen shot 2015-03-29 at 21 42 12](https://cloud.githubusercontent.com/assets/71105/6889098/a9252408-d65c-11e4-9e58-12f2a91bf897.png)

**Comment by rogual** [comment]
Thanks, fixed in https://github.com/rogual/neovim-dot-app/commit/f73bfb6864b5157d1a3382026335119324ae1c79.
