### ISSUE TITLE
Disable / rewire key bindings?

### ISSUE THREAD

**Issue by jamischarles** [rogual/neovim-dot-app#177]
Currently, I have this in my `~/.gvimrc` which disables macVim keybindings I don't want:

```vim
" Rewire MacVim Cmd T so we can use that for CTRL-P http://superuser.com/questions/249448/macvim-re-map-command-key-combinations-like-d-f
if has("gui_macvim")
  "https://github.com/carlhuda/janus/blob/0e34a62fac3a38ccc459bf3a6dab6ef1ec6dc9a5/janus/vim/gvimrc#L5-8
  "macmenu &File.New\ Tab key=<nop>
  macmenu &File.New\ Tab key=<D-S-t>

  macmenu &File.Save key=<nop>
endif
```

Is there any way to do the same here? I have certain keybindings that neovim.app is interfering with. Love it btw!

**Comment by rogual** [comment]
You can set new shortcuts like this:
```
call MacMenu("Window.New Tab", "T-S-t")
```

Removing shortcuts is actually not possible at the moment, but give me a minute.

**Comment by rogual** [comment]
OK, as of 71c96b3a31dfb58444773955399752d3d7fdc7bb you can now remove shortcuts like this:
```
call MacMenu("File.Save", "")
```

**Comment by rogual** [comment]
Still missing is a nice way to detect Neovim.app — see https://github.com/rogual/neovim-dot-app/issues/91

**Comment by jamischarles** [comment]
Thx! Whats the best way to get this? When will this be on brew?

**Comment by rogual** [comment]
You can always get the latest commits with `brew reinstall --HEAD neovim-dot-app`

**Comment by jamischarles** [comment]
So this worked really great, also implemented `if exists("neovim_dot_app")`.

Here's something really weird though. I can open a separate issue for this if you want, just let me know:
```vim
" This maps to cmd-/ in MacVim
  map <D-/> gcc
" This maps to cmd-/ in Neovim.app
  map <T-/> gcc
```

Is this not a vim-native thing, but something Macvim and Neovim have chosen? I assumed `<D>` was mapped to the `cmd` key universally, but maybe that's not the case?

**Comment by rogual** [comment]
Vim has a small set of modifiers that it knows about, and each has a fixed letter.

MacVim chose `D-` for Command, which isn't one of the allowed letters, but, since they're a fork of Vim itself, they just patched in support for it.

Since we're just a separate app talking to Neovim, we can't do that, and we have to use one of Vim's available modifiers. My choices were I think `S-` and `T-`.

**Comment by jamischarles** [comment]
Ah, makes sense. Would be nice if Neovim just picked one and supported it, but perhaps they want to stay flexible.

**Comment by pbiggar** [comment]
I couldn't get this to work with
`call MacMenu("Window.New Tab", "")`
but it works fine with
`call MacMenu("Window.Print", "")`

**Comment by rogual** [comment]
What are you trying to do? `call MacMenu("Window.New Tab", "")` is the command to remove the keyboard shortcut (cmd-t) from the New Tab menu item.

**Comment by pbiggar** [comment]
Yes, that's what I was trying to do. It didn't work (after calling that, cmd-t still made a new tab).

**Comment by rogual** [comment]
Haha!

Well, that's odd, it seems to work for me. Does the shortcut still show up in the menu? If not, maybe you also have a Vim-level binding for cmd-t? MacMenu just removes the Cocoa binding.
