### ISSUE TITLE
Problem selecting completion options presented by YouCompleteMe

### ISSUE THREAD

**Issue by ManuDevelopia** [rogual/neovim-dot-app#178]
While using YouCompleteMe (https://github.com/Valloric/YouCompleteMe)I have problems when I try to select a proposed autocomplete option (specially choosing python modules).

I suspect that the problem can be originated by the Preview, which present documentation about the option on the Scratch area. If I use "set completeopt-=preview" in the config, the problem seem to disappear, but no documentation is shown, and sometimes is useful.

Yosemite - neovim-dot-app today version

**Comment by rogual** [comment]
What happens, exactly? Why can't you select an option?

**Comment by ManuDevelopia** [comment]
The problem is that the proposed options are shown on the screen, but when you try to go down to select one suddenly disappear.  
![screen shot 2015-11-11 at 23 30 45](https://cloud.githubusercontent.com/assets/43015/11104965/4d0c0056-88cc-11e5-8ca3-8c981dd0c77f.png)

**Comment by joshbode** [comment]
I am seeing this issue, too (`brew reinstall --HEAD neovim neovim-dot-app` on 2015-11-15).

The preview works fine from `nvim` in a terminal, displaying function documentation in a split window at the top of the screen. However, in neovim-dot-app the split window only appears briefly before disappearing and closing the completion list.

**Comment by rogual** [comment]
It's possible that Neovim.app doesn't play well with plugins that talk to Neovim over RPC. Need to look into this.

**Comment by rogual** [comment]
I did manage to reproduce a similar issue with ClangComplete, but it seems to have gone away with latest HEAD.

Could you check and see if this one has gone away too?

**Comment by ManuDevelopia** [comment]
Now seems to be working ok!!! thanks a lot 
![screen shot 2016-06-17 at 18 38 04](https://cloud.githubusercontent.com/assets/43015/16157888/d87eeffa-34ba-11e6-9962-f9b2149b1b06.png)

**Comment by bambu** [comment]
This was reported as working. Closing.
