### ISSUE TITLE
Window position always defaults to bottom left corner

### ISSUE THREAD

**Issue by dixius99** [rogual/neovim-dot-app#179]
I've noticed that when opening the neovim-dot-app, the window always appears in the bottom left corner of my screen, regardless of the window position when I closed it. This is different from most of the Mac apps I've checked, which remember their window position when closed, so they open in the same place the next time.

**Comment by bambu** [comment]
I have experienced something similar to this. However, it only happens when I use an app like Spectacle to resize a window then quit. If I drag the window or maximize  the position then quit is remembered

**Comment by dixius99** [comment]
That sounds right. I see you had a pull request a while ago that changed the way height and width are saved. I tried to look in the Apple docs re: how to save window position, but couldn't figure it out.
