### ISSUE TITLE
Weird Font Rendering Issues

### ISSUE THREAD

**Issue by amadeus** [rogual/neovim-dot-app#18]
Seems I can see any fonts being rendered, until random types of redraw events take place. 

Neovim in terminal (looks fine):
![terminal neovim](https://dl.dropboxusercontent.com/s/6y53f32dscqbbzr/neovim-dot-app__tubez_in_progress__nvim_2015-03-30_11-41-51.png?dl=0)

Neovim in Neovim dot app (broken):
![neovim dot app](https://dl.dropboxusercontent.com/s/er3c8u0anhhyv7n/Untitled_2015-03-30_11-41-58.png?dl=0)

If I try to enter a command, I see the cursor move around, but no text:
![neovim command](https://dl.dropboxusercontent.com/s/svwvthr4tdgcc9m/Untitled_2015-03-30_11-42-47.png?dl=0)

And finally, if I load a file, I still get nothing, however if I use `ctrl - e` to scroll, the text appears:
![text shows](https://dl.dropboxusercontent.com/s/312705vyysi86w7/.vimrc_2015-03-30_11-46-02.png?dl=0)

Also, this is with default nvim settings, I have no .nvimrc being loaded.

**Comment by rogual** [comment]
Oh man, this is going to be impossible to debug — it doesn't happen for me at all. Could I get you to try a couple of things?

* `rm -rf build` and build again. Shouldn't need to, but it's my first resort when things get weird.
* Try latest master on the off-chance that fixes it

**Comment by amadeus** [comment]
Hmm, tried what you mentioned, still broken unfortunately. Running 10.10.2 and neovim reports this version in `:version` command:

NVIM 0.0.0-alpha+201503292107

if that helps at all.

**Comment by rogual** [comment]
OK, thanks for trying that. You're not the only person reporting rendering bugs since the last redraw optimization was merged so I've reverted it. Let me know if that fixes it for you.

**Comment by amadeus** [comment]
Yup, it seems after that revert that it works fine, thanks!
