### ISSUE TITLE
Unable to map <M-}> etc because gui is capturing the key bindings first

### ISSUE THREAD

**Issue by robacarp** [rogual/neovim-dot-app#183]
I'm experimenting with the ```:terminal``` buffers today and tried this:

```viml
:tnoremap <D-}> <C-\><C-n>:tabnext
:tnoremap <D-{> <C-\><C-n>:tabprev
```

Which I was hoping would give me the ability to switch tabs directly from the terminal insert mode, similar to how it works with regular buffers. The command is basically ignored, from what I can tell, because neovim-dot-app is listening to ```command-{``` and manually issuing the ```:tabprev``` command. 

What results is a terminal with the text :tabprev<Enter> having been sent, which triggers various error messages depending on the active context in the terminal.

**Comment by rogual** [comment]
Thanks for the bug report.

Our menu system uses Vim's `menu` family of commands. `:menu` is a Vim feature where menu names can be associated with commands. Each menu item can have a different binding for different modes. Bindings are set with `:nmenu`, `:vmenu`, etc.

But, AFAIK, terminal mode is not integrated with Vim's menu system and menu items cannot have terminal bindings. See other discussion here: https://github.com/rogual/neovim-dot-app/issues/143

As a workaround, you should be able to unbind those keyboard shortcuts from the menus, then your `tnoremap` bindings should be able to take effect. Try this:

```
call MacMenu("Window.Next Tab", "")
call MacMenu("Window.Previous Tab", "")
```
