### ISSUE TITLE
Looks very weird on load

### ISSUE THREAD

**Issue by owais** [rogual/neovim-dot-app#185]
<img width="835" alt="screen shot 2015-11-21 at 5 24 37 am" src="https://cloud.githubusercontent.com/assets/46186/11314892/2fc2bc06-9010-11e5-91c6-4d402b389a0e.png">

^ This is what Neovim-dot-app looks like when I start it.

If I go into the solairized menu and change something or if I manually set colourscheme to solarized, it immediately looks the way it is supposed to,

<img width="835" alt="screen shot 2015-11-21 at 5 26 32 am" src="https://cloud.githubusercontent.com/assets/46186/11314910/7205e64c-9010-11e5-9f1e-04414801020a.png">

**Comment by ManuDevelopia** [comment]
@owais is _colorscheme solarized_ included in your init.vim? Are you using https://github.com/altercation/vim-colors-solarized? I´m using this and it works ok for me.

**Comment by owais** [comment]
Yes, that's what I'm using and I've it enabled. It works fine in vim.

**Comment by rogual** [comment]
How about in terminal Neovim?

**Comment by owais** [comment]
That works perfectly

**Comment by rogual** [comment]
Would you be happy to post your vimrc? If so I'll use it and see if I can reproduce the issue.

**Comment by owais** [comment]
https://gist.github.com/owais/da821be8b6dadd8ad70d

There is a lot of cruft accumulated over the years in there.

**Comment by owais** [comment]
Looks like there some issue with `set enc=utf-8`.  I removed that and now it works perfectly.

**Comment by rogual** [comment]
This might be due to the intersection of two Neovim peculiarities:
- We source vimrc's twice to workaround neovim's new gui_loaded behaviour
- In Neovim `enc` can't be set after startup
