### ISSUE TITLE
Multiple windows

### ISSUE THREAD

**Issue by kristian-puccio** [rogual/neovim-dot-app#186]
Be great to be able to open multiple windows.

I use this feature in macvim as each window get's it's own current directory, so things like CTRL-p and Ag work independently for each window.

**Comment by rogual** [comment]
You should be able to do File -> New Window

**Comment by kristian-puccio** [comment]
I don't see that... I only see New Tab.

I've reinstalled from homebrew using --HEAD option. Not sure if that has
anything to do with it.

**Comment by rogual** [comment]
It sounds like you’ve got an old version. Things to try:

1. brew reinstall —HEAD neovim-dot-app should bring you up to date. Sounds like maybe you’ve already tried that though.
2. Can you find out which commit Homebrew has installed? I don’t know how to do this.
3. Maybe you have the app installed twice by accident? Make sure you’re running the copy in /usr/local/Cellar/neovim-dot-app

**Comment by kristian-puccio** [comment]
Sorry you are quite correct. I was opening an old copy I compiled manually.

Thanks
