### ISSUE TITLE
Homebrew throws error "Failed to download resource"

### ISSUE THREAD

**Issue by AmaruCoder** [rogual/neovim-dot-app#188]
I'm trying to install `neovim-dot-app` using Homebrew, but I get the error message: `Failed to download resource "openssl"` See below:

brew install --HEAD neovim-dot-app
==> Installing neovim-dot-app from rogual/homebrew-neovim-dot-app
==> Installing dependencies for neovim-dot-app: neovim, openssl, python
==> Installing neovim-dot-app dependency: neovim
==> Cloning https://github.com/neovim/neovim.git
Cloning into '/Library/Caches/Homebrew/neovim--git'...
remote: Counting objects: 2017, done.
remote: Compressing objects: 100% (1851/1851), done.
remote: Total 2017 (delta 163), reused 1395 (delta 146), pack-reused 0
Receiving objects: 100% (2017/2017), 6.99 MiB | 1.32 MiB/s, done.
Resolving deltas: 100% (163/163), done.
Checking connectivity... done.
==> Checking out branch master
==> Downloading https://github.com/libuv/libuv/archive/v1.4.2.tar.gz
######################################################################## 100.0%
==> Downloading https://github.com/msgpack/msgpack-c/archive/cpp-1.0.0.tar.gz
######################################################################## 100.0%
==> Downloading http://luajit.org/download/LuaJIT-2.0.3.tar.gz
######################################################################## 100.0%
==> Downloading https://github.com/keplerproject/luarocks/archive/0587afbb5fe8ceb2f2eea16f486bd6183bf02f29.tar.gz
######################################################################## 100.0%
==> Downloading https://github.com/mauke/unibilium/archive/v1.1.2.tar.gz
######################################################################## 100.0%
==> Downloading https://github.com/neovim/libtermkey/archive/8c0cb7108cc63218ea19aa898968eede19e19603.tar.gz
######################################################################## 100.0%
==> Downloading https://github.com/neovim/libvterm/archive/1b745d29d45623aa8d22a7b9288c7b0e331c7088.tar.gz
######################################################################## 100.0%
==> Downloading https://github.com/jemalloc/jemalloc/archive/3.6.0.tar.gz
######################################################################## 100.0%
==> make CMAKE_BUILD_TYPE=RelWithDebInfo DEPS_CMAKE_FLAGS=-DUSE_BUNDLED_BUSTED=OFF CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PR
==> Caveats
If you want support for Python plugins such as YouCompleteMe, you need
to install a Python module in addition to Neovim itself.

See :h nvim-python-quickstart for more information.
==> Summary
🍺  /usr/local/Cellar/neovim/HEAD: 1322 files, 21M, built in 4.9 minutes
==> Installing neovim-dot-app dependency: openssl
==> Downloading https://www.openssl.org/source/openssl-1.0.2a.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://raw.githubusercontent.com/DomT4/LibreMirror/master/OpenSSL/openssl-1.0.2a.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "openssl"
Download failed: https://raw.githubusercontent.com/DomT4/LibreMirror/master/OpenSSL/openssl-1.0.2a.tar.gz

**Comment by joshbode** [comment]
Looks like that is an error in the formula for openssl (as a dependency of neovim-dot-app).
If you do a `brew update` this should be fixed.

**Comment by AmaruCoder** [comment]
I followed the instructions, and the installation went further along. This time around it gave me a different message that referred me to `neovim-dot-app`:

brew reinstall --HEAD neovim-dot-app
==> Reinstalling rogual/neovim-dot-app/neovim-dot-app
==> Installing dependencies for rogual/neovim-dot-app/neovim-dot-app: scons, msgpack, sqlite, openssl, python
==> Installing rogual/neovim-dot-app/neovim-dot-app dependency: scons
==> Downloading https://homebrew.bintray.com/bottles/scons-2.4.1.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring scons-2.4.1.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/scons/2.4.1: 208 files, 2.6M
==> Installing rogual/neovim-dot-app/neovim-dot-app dependency: msgpack
==> Downloading https://homebrew.bintray.com/bottles/msgpack-1.2.0.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring msgpack-1.2.0.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/msgpack/1.2.0: 479 files, 5.9M
==> Installing rogual/neovim-dot-app/neovim-dot-app dependency: sqlite
==> Downloading https://homebrew.bintray.com/bottles/sqlite-3.9.2.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring sqlite-3.9.2.el_capitan.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X provides an older sqlite3.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/sqlite/lib
    CPPFLAGS: -I/usr/local/opt/sqlite/include

==> Summary
🍺  /usr/local/Cellar/sqlite/3.9.2: 9 files, 2.8M
==> Installing rogual/neovim-dot-app/neovim-dot-app dependency: openssl
==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2d_1.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring openssl-1.0.2d_1.el_capitan.bottle.tar.gz
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

This formula is keg-only, which means it was not symlinked into /usr/local.

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include

==> Summary
🍺  /usr/local/Cellar/openssl/1.0.2d_1: 464 files, 17M
==> Installing rogual/neovim-dot-app/neovim-dot-app dependency: python
==> Downloading https://www.python.org/ftp/python/2.7.10/Python-2.7.10.tgz
######################################################################## 100.0%
==> Downloading https://bugs.python.org/file30805/issue10910-workaround.txt
######################################################################## 100.0%
==> Downloading https://bugs.python.org/file40479/xcode-stubs-2.7.patch
######################################################################## 100.0%
==> Patching
patching file Include/pyport.h
Hunk #1 succeeded at 713 (offset 14 lines).
Hunk #2 succeeded at 736 (offset 14 lines).
patching file Lib/distutils/ccompiler.py
patching file Lib/distutils/unixccompiler.py
==> ./configure --prefix=/usr/local/Cellar/python/2.7.10_2 --enable-ipv6 --datarootdir=/usr/local/Cellar/python/2.7.10_2
==> make
==> make install PYTHONAPPSDIR=/usr/local/Cellar/python/2.7.10_2
==> make frameworkinstallextras PYTHONAPPSDIR=/usr/local/Cellar/python/2.7.10_2/share/python
==> Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-18.3.1.tar.gz
######################################################################## 100.0%
==> Downloading https://pypi.python.org/packages/source/p/pip/pip-7.1.2.tar.gz
######################################################################## 100.0%
==> Downloading https://pypi.python.org/packages/source/w/wheel/wheel-0.26.0.tar.gz
######################################################################## 100.0%
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall python`
==> Caveats
Pip and setuptools have been installed. To update them
  pip install --upgrade pip setuptools

You can install Python packages with
  pip install <package>

They will install into the site-package directory
  /usr/local/lib/python2.7/site-packages

See: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Homebrew-and-Python.md

.app bundles were installed.
Run `brew linkapps python` to symlink these to /Applications.
==> Summary
🍺  /usr/local/Cellar/python/2.7.10_2: 5827 files, 91M, built in 2.7 minutes
==> Installing rogual/neovim-dot-app/neovim-dot-app
==> Cloning https://github.com/rogual/neovim-dot-app.git
Cloning into '/Library/Caches/Homebrew/neovim-dot-app--git'...
remote: Counting objects: 51, done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 51 (delta 0), reused 21 (delta 0), pack-reused 0
Unpacking objects: 100% (51/51), done.
Checking connectivity... done.
==> Checking out branch master
==> make NVIM=/usr/local/opt/neovim/bin/nvim
Last 15 lines from /Users/Amaru/Library/Logs/Homebrew/neovim-dot-app/01.make:
clang++ -o build/font.o -c -std=c++11 -stdlib=libc++ -g -Wno-deprecated-register -Ibuild -Isrc src/font.mm
clang++ -o build/graphics.o -c -std=c++11 -stdlib=libc++ -g -Wno-deprecated-register -Ibuild -Isrc src/graphics.mm
clang++ -o build/input.o -c -std=c++11 -stdlib=libc++ -g -Wno-deprecated-register -Ibuild -Isrc src/input.mm
clang++ -o build/keys.o -c -std=c++11 -stdlib=libc++ -g -Wno-deprecated-register -Ibuild -Isrc src/keys.mm
clang++ -o build/main.o -c -std=c++11 -stdlib=libc++ -g -Wno-deprecated-register -Ibuild -Isrc src/main.mm
clang++ -o build/menu.o -c -std=c++11 -stdlib=libc++ -g -Wno-deprecated-register -Ibuild -Isrc src/menu.mm
gperf -cCD -L C++ -Z RedrawHash -t src/redraw.gperf > build/redraw-hash.gen.h
clang++ -o build/redraw.o -c -std=c++11 -stdlib=libc++ -g -Wno-deprecated-register -Ibuild -Isrc src/redraw.mm
clang++ -o build/view.o -c -std=c++11 -stdlib=libc++ -g -Wno-deprecated-register -Ibuild -Isrc src/view.mm
clang++ -o build/window.o -c -std=c++11 -stdlib=libc++ -g -Wno-deprecated-register -Ibuild -Isrc src/window.mm
clang++ -o build/Neovim.app/Contents/MacOS/Neovim build/client.o build/process.o build/rpc.o build/vim.o build/vimutils.o build/app.o build/font.o build/graphics.o build/input.o build/keys.o build/main.o build/menu.o build/redraw.o build/view.o build/window.o -lc++ -lmsgpack -framework Cocoa -framework Carbon
ld: library not found for -lmsgpack
clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [build/Neovim.app/Contents/MacOS/Neovim] Error 1
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/rogual/homebrew-neovim-dot-app/issues

**Comment by joshbode** [comment]
Looks similar to Issue #184. I had this error a while back, too. Can't recall the exact solution, but try running `xcode-select --install` and see if that helps.
Not sure if this helped me, but I may have had to open XCode.app once, too.

**Comment by AmaruCoder** [comment]
Thank you for the help. When I run `xcode-select --install` I get the following error:

xcode-select --install
xcode-select: error: no developer tools were found, and no install could be requested (perhaps no UI is present), please install manually from 'developer.apple.com'.

**Comment by joshbode** [comment]
Do you have _Command Line Tools for XCode_ installed?
If not, you can download them from here and install: https://developer.apple.com/downloads/
Pick the one to match the version of _XCode_ you have installed.

**Comment by AmaruCoder** [comment]
Yes, I do have XCode installed, and current to the latest version (7.1.1 7B1005).

**Comment by joshbode** [comment]
That's good. How about the Xcode Command Line Tools?
- Is there anything installed at `/Library/Developer/CommandLineTools`?
- What are the outputs of `xcode-select -p` and `gcc --version`?
- Have you ever started up the Xcode application (Xcode.app)?
  Run `open /Applications/Xcode.app` and see if this has any affect on being able to install

**Comment by AmaruCoder** [comment]
- The output for `xcode-select -p` is:
    `/Applications/Xcode.app/Contents/Developer`
- And for `gcc --version` is:

Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin15.0.0
Thread model: posix

- Your third question seems to imply that only registered developers can install `neovim-dot-app`. If that is the case, would it be possible to have the binaries ready to download, as it is the case for `vim`?

**Comment by cserb** [comment]
Any news here? @AmaruCoder have you been able to solve the problem?
I have the same error even thought everything is installed.

**Comment by AmaruCoder** [comment]
No luck at all. I have abandon Neovim for the time being. In particular now that Vim's install for OS X has its own upgrading function which works seamlessly.

**Comment by bambu** [comment]
I had the same problem as @AmaruCoder's Dec 3, 2015 post when installing via brew on a different Mac yesterday. 

Here's what I did to resolve it. Not sure if all of these steps are necessary, but it is what i did. 

1. Uninstall neovim and neovim-dot-app. Make sure that all versions are uninstalled. (I had 2 different neovims)
2. upgrade brew
3. untap / retap from rogual/neovim-dot-app and neovim
4. install the --HEAD versions of both neovim and neovim-dot-app

I think that box was 10.11.3 with Xcode 7.3

**Comment by kamleshwebtech** [comment]
I am getting error "Failed to download resource "jemalloc_bottle_manifest" while installing ffmpeg by brew. any suggestion? Thanks a lot.
