### ISSUE TITLE
Compilation fails on master

### ISSUE THREAD

**Issue by bulkan** [rogual/neovim-dot-app#19]
Hi there,

Can't seem to be able to compile the latest master. I went back and at 1a148bf143ef4aa13089b6573c11781ca2570eab is when I can successfully compile.

NVIM 0.0.0-alpha+201503270525 (compiled Mar 31 2015 16:41:18)
msgpack-c: 1.0.1

## System Log

```
Mar 31 16:57:28 spock com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.system): Caller not allowed to perform action: open.81325, action = service submission, code = 1: Operation not permitted, uid = 501, euid = 501, gid = 20, egid = 20, asid = 100005
Mar 31 16:57:29 spock com.apple.xpc.launchd[1] (com.apple.ReportCrash[81338]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.ReportCrash
```

[nvim crash log](https://gist.github.com/bulkan/5f86dc261d041ddb070a)

**Comment by rogual** [comment]
A lot of people have been having problems since a certain commit which I've just reverted — see if it works for you now.

**Comment by bulkan** [comment]
All good now thanks :)
