### ISSUE TITLE
Unable to map <C-Tab> and <C-S-Tab>

### ISSUE THREAD

**Issue by rolandcrosby** [rogual/neovim-dot-app#190]
I attempted to map `<C-Tab>` and `<C-S-Tab>` to switch between tabs, as follows:

```vim
map <C-Tab> gt
map <C-S-Tab> gT
```

This works correctly in MacVim, and [apparently works in gVim as well](http://stackoverflow.com/a/21555881), but does not work in neovim-dot-app.

**Comment by rogual** [comment]
Probably to do with the fact that tab itself is C-I. Might be fixable, will have a look.

**Comment by bambu** [comment]
Looks like `<C-Tab>` and `<C-S-Tab>` are never interpreted by the `-keyDown:` event. This same problems appears when trying those keys in terminal neovim both on iTerm and Terminal. 

MacVim / VimR do it by handling it on the NSApplication's `-sendEvent:` event and making sure that it gets passed as a `-keyDown:` event. There does not appear to be an equivalent type of event for `NSApplicationDelegate`. This may require switching `app.mm` from `NSApplicationDelegate` to `NSApplication`. Not sure what all this entails. @rogual any reason why you didn't use `NSApplication` ?

**Comment by bambu** [comment]
nvm. found a better solution that doesn't require `NSApplication`

**Comment by bambu** [comment]
This should also be closed as solution has been merged
