### ISSUE TITLE
CTRL-F does nothing

### ISSUE THREAD

**Issue by mattsawyer77** [rogual/neovim-dot-app#194]
For some reason, only in Neovim.app, CTRL-f doesn't seem to do anything. I don't have it mapped (as far as I can tell anyway) to anything. It works fine in terminal nvim.

**Comment by rogual** [comment]
What are you expecting it to do?

**Comment by mattsawyer77** [comment]
@rogual page down. I also tried mapping it like `map <C-f> <C-d><C-d>` but that didn't work.

**Comment by rogual** [comment]
Huh, weird. Works for me. Can you start with `-u NONE` to disable user settings & see if it still happens?

**Comment by mattsawyer77** [comment]
@rogual not sure how to do that when launching Neovim.app (I currently do `open -a /Applications/Neovim.app/Contents/MacOS/Neovim` but adding `-u NONE` to this results in an error.

**Comment by rogual** [comment]
With `open` you have to make it `--args -u NONE`

**Comment by mattsawyer77** [comment]
@rogual thanks. I was also able to open just by calling the executable directly. CTRL-f is working, so I must have some plugin or map somewhere that is preventing it. Thanks for your help!

**Comment by mattsawyer77** [comment]
Anyone have any clues for how I can find what's preventing CTRL-f from working? I've combed through the output of :map and :map! and have come up with nothing. I have a lot of plugins and, unless there is no other way, didn't want to go down the road of disabling them one by one to find it.

**Comment by mattsawyer77** [comment]
For posterity, it turned out to be a mapping I created in OS X Keyboard preferences.
