### ISSUE TITLE
No GUI on startup

### ISSUE THREAD

**Issue by andrasbarany** [rogual/neovim-dot-app#203]
Hi, I've been experiencing trouble with starting neovim.app.
The GUI used to load just fine but at some point this changed: when starting neovim.app (via Finder, launcher or command line) does not show a window. I think the reason might have been that the font I had selected was deleted and on the next startup gnvim didn't know what to load.
Pressing CMD-+ makes an empty titlebar appear in the bottom-left corner as shown on one of the screenshots. This titlebar can be moved and resized but there is nothing more.
I can “open” files, such that the titlebar shows the filename, and I can use “ZZ” and other commands, but I don't see anything.

I tried deleting and reinstalling, and everything compiles fine, but the window never loads.

![screen shot 2016-01-21 at 16 44 19](https://cloud.githubusercontent.com/assets/11692974/12485316/885c327e-c05e-11e5-86b9-fda8f4fe0c88.png)
![screen shot 2016-01-21 at 16 43 00](https://cloud.githubusercontent.com/assets/11692974/12485317/885dfc3a-c05e-11e5-8342-a9faa5333777.png)

**Comment by rogual** [comment]
That... is a new one on me. If it is font-related, mabe try deleting Neovim.app's user settings:

`defaults delete uk.foon.neovim`

**Comment by andrasbarany** [comment]
No effect, unfortunately, the same thing happens.
