### ISSUE TITLE
where is the gui config file?

### ISSUE THREAD

**Issue by acerphoenix** [rogual/neovim-dot-app#209]
sorry it's not a issue,but like macvim there is a .gvimrc for gui, how do i know the gui config file for neovim-dot-app?

**Comment by rogual** [comment]
It's the same file as for Neovim itself, which is `~/.config/nvim/init.vim`

As for what to put in the file, see https://github.com/rogual/neovim-dot-app/blob/master/res/nvimrc

Starting on line 12 you can see the definitions of all gui-specific functions. Call these with `call` statements in your vimrc to configure.

You can use `if exists('neovim_dot_app')` to only run stuff when in Neovim.app, if you want your file to still be compatible with terminal Neovim.

**Comment by acerphoenix** [comment]
OK,thank you,i'll try it. it's quite different from the .gvimrc.
