### ISSUE TITLE
Airline separators look weird

### ISSUE THREAD

**Issue by ManuDevelopia** [rogual/neovim-dot-app#215]
After a long time without  updating neovim-dot-up, I made it and now this is how vim-airline is shown, the separators look weird. I´m using hack font.

![screen shot 2016-02-22 at 22 12 47](https://cloud.githubusercontent.com/assets/43015/13232969/b79c4bfc-d9b1-11e5-8e3a-e46012328fc8.png)

But this should be something like: 
![screen shot 2016-02-22 at 22 20 26](https://cloud.githubusercontent.com/assets/43015/13233127/848a5a28-d9b2-11e5-9fec-4ade7e478dad.png)

**Comment by rogual** [comment]
I run vim-airline and I can't reproduce this. I use the font "Monaco for Powerline".

**Comment by ManuDevelopia** [comment]
I tried to change, but same result. I will test on my other devices.

**Comment by mikew** [comment]
I'm seeing it with Monaco for Powerline:

<img width="968" alt="screen shot 2016-02-25 at 10 26 08 pm" src="https://cloud.githubusercontent.com/assets/4729/13354330/b4f6b8c6-dc70-11e5-9125-61d6d42ee43c.png">

And if I instal `vim-airline-themes`, it goes grayscale for some reason:

<img width="875" alt="screen shot 2016-02-26 at 10 10 06 am" src="https://cloud.githubusercontent.com/assets/4729/13354398/2cde829c-dc71-11e5-8e92-08885ebe2b73.png">

When running `nvim` from terminal things are normal.

**Comment by U47** [comment]
I'm seeing the same as everyone else. This is using [Input font](http://input.fontbureau.com).

Neovim in iTerm2:
![neovim](https://cloud.githubusercontent.com/assets/573316/13385852/cd206b42-de62-11e5-8bac-824fb8c5225b.png)

Neovim.app
![neovim-dot-app](https://cloud.githubusercontent.com/assets/573316/13385853/cd3b62f8-de62-11e5-92f9-c9bae49af989.png)

**Comment by mikew** [comment]
@ManuDevelopia @U47 Could you try this?

```bash
echo 'let $NVIM_TUI_ENABLE_TRUE_COLOR=1' | cat - /Applications/Neovim.app/Contents/Resources/nvimrc | tee /Applications/Neovim.app/Contents/Resources/nvimrc
```

(Add `let $NVIM_TUI_ENABLE_TRUE_COLOR=1` to the beginning of `/Applications/Neovim.app/Contents/Resources/nvimrc`)

That seems to fix my issues with airline. If it fixes your issues as well I'll send a PR.

<img width="932" alt="screen shot 2016-03-01 at 12 08 37 am" src="https://cloud.githubusercontent.com/assets/4729/13417386/d57c49fc-df41-11e5-862f-5757bd43a40b.png">

**Comment by dixius99** [comment]
@mikew This worked for me!

**Comment by ManuDevelopia** [comment]
Thanks @mikew this worked for me too

**Comment by U47** [comment]
Haha. I added that to a shell alias for nvim to enable übercolour in iTerm2. I should have thought to add that to Neovim.app's nvimrc.

Thanks, @mikew. She works!

**Comment by ManuDevelopia** [comment]
For me this issue is back, any one else?

**Comment by dixius99** [comment]
Mine's still okay.

**Comment by mikew** [comment]
It's back for me too. @ManuDevelopia try adding `set termguicolors` in your vimrc before setting your colorscheme.

**Comment by ManuDevelopia** [comment]
Thanks again @mikew! separators are now ok!

**Comment by geraldus** [comment]
For me the perfect solution was to prepend to `/Applications/Neovim.app/Contents/Resources/nvimrc` following line:

```vim
set termguicolors
```

This gives proper look of powerline symbols both for __Neovim GUI__ and __nvim__ in the shell.
