### ISSUE TITLE
enhancement request: allow text selection/copying in non-editing areas

### ISSUE THREAD

**Issue by mattsawyer77** [rogual/neovim-dot-app#216]
Not sure how possible this is. But it would be convenient if we could select/copy text from non-editing areas, e.g. the output of :messages.

**Comment by rogual** [comment]
Two ways of doing this:

- Get the change made in neovim itself, then no changes needed here.

- Add a separate kind of mouse selection to Neovim.app. When used, mouse commands are not sent to Neovim but processed directly in Neovim.app. Keep a record of which character cells are selected. Make the copy command behave differently when in this mode. This also requires keeping a buffer containing all the text currently on the screen, which we don't do right now.

**Comment by rogual** [comment]
Depending on your needs, you might be able to get by with something like

`:tabnew | :redir @a | :silent messages | :redir END | :normal "ap`

which will open :messages in an ordinary buffer. It's not as good as having the suggested feature, but it might be enough for some use cases.

**Comment by mattsawyer77** [comment]
@rogual thanks for the tip. that solves my concerns in a flexible way.
