### ISSUE TITLE
command-W

### ISSUE THREAD

**Issue by andreiamatuni** [rogual/neovim-dot-app#219]
Is it possible to make command-W close the current pane rather than the whole neovim app? This would be really helpful when working with lots of tabs and split panes

**Comment by rogual** [comment]
Yes, first remove ⌘W from the menu item:
```call MacMenu("Window.Close Tab", "")```

Then you can map `<D-w>` to whatever you like.

**Comment by andreiamatuni** [comment]
cool, thanks

**Comment by JackCA** [comment]
@andreiamatuni were you able to persist this somehow? What did you end up doing?

**Comment by andreiamatuni** [comment]
@JackCA ended up just sticking to macvim for the time being. Waiting for nvim to get more stable and have more reasons to use over regular vim.

**Comment by JackCA** [comment]
@andreiamatuni ah, okay. Thanks for the quick followup. I avtually just got this working by putting the following in my nvim/init.vim (in case anyone else is also interested since this is the default macvim behavior):

```
if exists("neovim_dot_app")
  call MacMenu("Window.Close Tab", "")
  map <D-w> :q <cr>
endif
```
