### ISSUE TITLE
Option to not anti-alias fonts

### ISSUE THREAD

**Issue by lewisthompson** [rogual/neovim-dot-app#220]
I use the Terminus (TTF) font which requires fonts are not anti-aliased.  In iTerm2 I have an option to disable anti-aliasing but this does not seem present in neovim-dot-app.  Could such an option be introduced to support this and similar fonts?

**Comment by F1LT3R** [comment]
+1

Not likely to use Neovim with aliased fonts.

**Comment by rogual** [comment]
Hey guys,

Thanks to @bambu's recent work you can now toggle antialiasing in your init.vim:

```
call MacSetFontShouldAntialias(0)
call MacSetFontShouldAntialias(1)
```
