### ISSUE TITLE
Dead keys issue - Greek

### ISSUE THREAD

**Issue by nrontsis** [rogual/neovim-dot-app#221]
Hi,

When writing Greek, I believe that there is a problem with accents. For example consider the case of writing the character `έ`. Inputing it in a typical Greek keyboard requires typing the following "buttons": `;e`. However this results in `΄ε`.

I think this is an issue with the fact that Greek uses `;` as a _deadkey_. I can see that bambu has pushed https://github.com/rogual/neovim-dot-app/commit/11a3d05262314067d7c863765a1ee8e2a877a35d in order to handle deadkeys. However, due to my inexperience with Objective-C, I am having a hard time finding the problem.

Do you have any suggestions?

_[I am using NVIM 0.1.3-dev, neovim-dot-app 0.1.2 on El Capitan]_

Cheers,

Nikitas

**Comment by bambu** [comment]
When I made that commit, I think I only tried the US and Spanish layouts. Seems like greek doesn't require pressing a modifier for the deadkey. working to fix this.

**Comment by nrontsis** [comment]
Thanks @bambu !

**Comment by bambu** [comment]
@nrontsis please checkout the PR and let me know if it works.

**Comment by nrontsis** [comment]
Fixed by PR https://github.com/rogual/neovim-dot-app/pull/246.
