### ISSUE TITLE
can not pick HEAD version of neovim dev version

### ISSUE THREAD

**Issue by ray-x** [rogual/neovim-dot-app#225]
nvim --version
NVIM 0.1.3-dev
Build type: Dev
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20160316-5920-rrdb0n/build/config -I/tmp/neovim20160316-5920-rrdb0n/src -I/tmp/neovim20160316-5920-rrdb0n/deps-build/usr/include -I/tmp/neovim20160316-5920-rrdb0n/deps-build/usr/include -I/tmp/neovim20160316-5920-rrdb0n/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20160316-5920-rrdb0n/deps-build/usr/include -I/tmp/neovim20160316-5920-rrdb0n/deps-build/usr/include -I/tmp/neovim20160316-5920-rrdb0n/deps-build/usr/include -I/tmp/neovim20160316-5920-rrdb0n/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim20160316-5920-rrdb0n/build/src/nvim/auto -I/tmp/neovim20160316-5920-rrdb0n/build/include
Compiled by rayx@Systems-iMac.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"

It seems that nvim changed the version to 0.1.3-dev instead of 0.1.3-223 and current SConstruct can not detect the version correctly.
I remove sys.exit(-1) to make the gnvim compile and it is running fine now.
Seems something need to change in line   
  fmt_ver = lambda ver: ('%s.%s.%s' if len(ver) == 3 else '%s.%s.%s-%s') % ver

**Comment by rogual** [comment]
Don't know why this happens but you're right, it's a pain. Looking into it here: https://github.com/neovim/homebrew-neovim/issues/135

**Comment by rogual** [comment]
Tempted to just remove the version check and let `--HEAD` users fend for themselves, now that we've got a stable version.

**Comment by rogual** [comment]
I've added logic to bypass this check if you get `-dev`. You'll have to manually make sure your Neovim is up to date (latest master).
