### ISSUE TITLE
Show only one app icon in Mac dock.

### ISSUE THREAD

**Issue by towry** [rogual/neovim-dot-app#226]
It seems there is no "new window" option of the app in the mac docker, when I open two neovim-dot-app, there will be two app icon in the docker, I think it would be better to group all the opened app into one icon in the docker.

**Comment by rogual** [comment]
This is with `gnvim`, right? If you use Cmd+N you should just have the one icon. Agreed this should be fixed.

**Comment by robguthrie** [comment]
Is this a matter of modifying gnvim? or should this be done on Neovim.app itself? Looking to the core devs to understand what the best way to do this is.

IE: Should I modify gnvim so it saves a PID, then check for existance of the PID to decide how to run?  If so, how should Neovim.app be run from the command line in a way that opens new window?

**Comment by rogual** [comment]
Just looked into this — we had `-n` as an argument to `open` in gnvim which always forced a new instance, as a workaround for some bug.

I have reverted this in https://github.com/rogual/neovim-dot-app/commit/2e5226b4cabfd732cd2d09fe2623300215a18cdb — try now.

**Comment by robguthrie** [comment]
Thanks @rogual. I've just removed the -n locally, but the behaviour is not correct. If Neovim.app is open, then the window is focused but no new file is opened.

So it will open a file if it's not already running, but it won't open a new file specified as first argument, if it's already running.

**Comment by rogual** [comment]
See latest couple of commits — should solve it.

**Comment by robguthrie** [comment]
Arrrh. Magic. So much better. Thank you!
