### ISSUE TITLE
Can not open the input method tool

### ISSUE THREAD

**Issue by towry** [rogual/neovim-dot-app#227]
In the neovim-dot-app, I can not use the Chinese Input Method Tool. But I can use the input method tool in Neovim on terminal.

**Comment by rogual** [comment]
Folding this into https://github.com/rogual/neovim-dot-app/issues/70

**Comment by asins** [comment]
I also encountered this problem.

install by `brew install neovim-dot-app` neovim-dot-app v0.1.5, and I try install last version(HEAD-269c16b), the input method cannot be opened.

Is this really a fix?

**Comment by rogual** [comment]
Please discuss this issue at #70
