### ISSUE TITLE
Path not set correctly

### ISSUE THREAD

**Issue by towry** [rogual/neovim-dot-app#228]
The app doesn't use the correct path, if I run command `echo $PATH` in the app, it returns an incomplete list of paths, much fewer than the result from running the command in neovim.

If I run `echom system('which npm')`, the result is `command not found`. In neovim the result is correct. I have a setting which is "system('npm bin')" and it cause an error: `"zsh:1: command not found: npm" is not an executable`

**Comment by rogual** [comment]
Probably fixed by https://github.com/rogual/neovim-dot-app/pull/260 or https://github.com/rogual/neovim-dot-app/pull/261 — reopen if I'm wrong.
