### ISSUE TITLE
Error: File is loaded in another buffer [gitgutter]

### ISSUE THREAD

**Issue by towry** [rogual/neovim-dot-app#229]
The issue happened when I use `:w` command to save the file, the whole error message is: 

```
Error detected while processing function gitgutter#process_buffer..gitgutter#diff#run_diff:
line 31:
E139: File is loaded in another buffer
```

This issue only happened in this app, I have never met this before.

**Comment by rogual** [comment]
Gitgutter gives me similar errors too. Usually if I restart the app, they go away for a while. At some point it will probably annoy me enough that I'll try to get to the bottom of the issue. Feel free to take a stab before then.

**Comment by azag0** [comment]
I'm getting this also in CLI neovim (current HEAD, gitgutter as well). Also happens only occasionally.

**Comment by jmcphers** [comment]
Also seeing this in HEAD of neovim + gitgutter + neovim.app (all three updated to HEAD today, May 4).

**Comment by adambiggs** [comment]
Also seeing this in neovim HEAD, but so far only when editing JSON files.

**Comment by vargad** [comment]
Exactly the same happens in vim 7.4 as well.
```
Error detected while processing function gitgutter#process_buffer..gitgutter#diff#run_diff:
line   35:
E139: File is loaded in another buffer
```

**Comment by mpercy** [comment]
I am also seeing this on latest gitgutter

**Comment by erikgrueter1** [comment]
+1

**Comment by Melkor333** [comment]
+1 having this when editing my .init.vim. In a session with different buffers & terminals, it occurs:

```
Error detected while processing function gitgutter#process_buffer..gitgutter#diff#run_diff:
line   35:
E139: File is loaded in another buffer
```

I haven't tested it any further but, having only nerdtree and init.vim opened (no other buffers), makes it behave normally.
But it occurs while editing the file (I guess whenever gitgutter reloads) and as soon as I save, it doesn't occur anymore.

**Comment by oldtimeguitarguy** [comment]
+1

**Comment by jeffrey-l-turner** [comment]
+1

**Comment by dnordberg** [comment]
+1

**Comment by blokezero** [comment]
Seems to happen with any kind of file when I have a quickfix window open.  Saving makes it go away.
