### ISSUE TITLE
White box at top of editor

### ISSUE THREAD

**Issue by bulkan** [rogual/neovim-dot-app#230]
Hi there,

When I start neovim.app I will consistently see a white box 

I'm running fe0c3127d088921a7adaaa9429bb110ff48fac3f of nvim 

If I keep restarting neovim.app it will at some time render properly without the white box

<img width="570" alt="screen shot 2016-03-23 at 2 11 05 pm" src="https://cloud.githubusercontent.com/assets/13985/13974618/614aac6e-f101-11e5-92fc-68232bb21505.png">

**Comment by rogual** [comment]
Does it go away if you resize the window?

**Comment by sehqlr** [comment]
Hey, I have this problem also, but it only happens when I'm doing the side-by-side tiling in El Capitan.

**Comment by rogual** [comment]
Closing after no response from OP. May be the same issue as https://github.com/rogual/neovim-dot-app/issues/269
