### ISSUE TITLE
Powerline glyphs rendering problem

### ISSUE THREAD

**Issue by iyee** [rogual/neovim-dot-app#238]
The newest PragmataPro font improves support for Vim Powerline: http://fsd.tumblr.com/post/34355224168/vim-powerline-inside-pragmatapro-v-0811

I configured the settings below:
```vim
set guifont=PragmataPro\ Mono:h11
let g:airline_powerline_fonts=1
```

and nvim in iterm2 looks great:
<img width="490" alt="screen shot 2016-04-06 at 10 45 06 pm" src="https://cloud.githubusercontent.com/assets/88564/14320860/40c7430a-fc49-11e5-9757-5f744ac740b4.png">

but Neovim.app is a totally mess:
<img width="1280" alt="screen shot 2016-04-06 at 10 46 07 pm" src="https://cloud.githubusercontent.com/assets/88564/14320890/6255b236-fc49-11e5-8f4b-8ab406a4cfb5.png">

**Comment by rogual** [comment]
Are you sure that powerline fonts setting is taking effect? Even in your iterm2 screenshot, the arrow shapes aren't showing.

**Comment by iyee** [comment]
<img width="500" alt="screen shot 2016-04-07 at 12 24 15 am" src="https://cloud.githubusercontent.com/assets/88564/14324373/1df233e0-fc57-11e5-857c-e0c5a24d8515.png">

Neovim in iTerm2.

**Comment by bambu** [comment]
@iyee did you select your font from `Edit->Show Fonts`? I don't think Neovim dot App supports gvim's `guifont`. Does it @rogual?

**Comment by iyee** [comment]
@bambu Thanks a lot, you found the solution.

**Comment by rogual** [comment]
Thanks @bambu. Yep, all `gui` stuff is deprecated or removed in Neovim (and hence Neovim.app)

**Comment by rogual** [comment]
If you do want to set your font from your `vimr`, you can still do:
```
call MacSetFont("Font Name", 12)
```

**Comment by iyee** [comment]
@rogual Thank you, it works.

**Comment by dylan-chong** [comment]
What about `set linespace = n`? There doesn't seem to be an option for that
