### ISSUE TITLE
LSOpenURLsWithRole() failed for the application /Users/rw/Work/neovim/build/Neovim.app with error -10810

### ISSUE THREAD

**Issue by romaninsh** [rogual/neovim-dot-app#239]
I have installed with brew reinstall --HEAD neovim-dot-app (ee82eb3), upon launching "gnvim" from command-line I receive this error:

$ gnvim 
LSOpenURLsWithRole() failed for the application /Users/rw/Work/neovim/build/Neovim.app with error -10810.

**Comment by romaninsh** [comment]
By editing https://github.com/rogual/neovim-dot-app/blob/master/gnvim#L23 into:

    open -n /Applications/Neovim.app $opt_blocking --args --cwd "$PWD" "$@"

I was able to fix application launching.

**Comment by romaninsh** [comment]
I have reomved ~/Work/neovim/* and "gnvim" works as expected, however I'd like to leave ticket for your consideration.

**Comment by rogual** [comment]
Thanks. Looks like the app cache is getting confused.
