### ISSUE TITLE
Gutter rendering cut off

### ISSUE THREAD

**Issue by jrolfs** [rogual/neovim-dot-app#240]
When switching to and from neovim-dot-app gutter symbols get cut off until they are re-rendered by the plugin that placed them ([neomake](https://github.com/benekastah/neomake) in this case).

This does not happen in iTerm and Terminal.

Is there a setting to make the gutter slightly larger?

Before:
![Before](http://d.pr/i/1cXaD+)

After:
![After](http://d.pr/i/19Ati+)

**Comment by rogual** [comment]
I'm guessing this isn't gutter-specific and will apply to any character that's wider than its cell.

It's difficult to know how to handle this, really. Vim is explicitly grid-oriented, and doesn't support proportional fonts. It does treat some characters as double-width and draws them across two cells, but if your font calls itself monospaced and some chars are too wide, it's never going to look great.

If we drew backgrounds first and then all chars on top, your case would start looking better, I think.

**Comment by jrolfs** [comment]
Is your suggestion feasible or should I plan on resizing the characters? :)

**Comment by rogual** [comment]
It's feasible, and I'd accept PRs that implemented it, but I'm not planning on writing it. Resizing them might be the way to go.

**Comment by jrolfs** [comment]
For the record, I recently switch to using the the Font Awesome glyphs in Fura Code from [nerd-fonts](https://github.com/ryanoasis/nerd-fonts) instead of whatever unicode glyph was being used by default in Neomake and this issue went away.

乁| ･ 〰 ･ |ㄏ

![ss](http://d.pr/i/1j7sg+)
