### ISSUE TITLE
clipboard copying of the trademark character is wrong.

### ISSUE THREAD

**Issue by pekcheey** [rogual/neovim-dot-app#245]
© ™ 2016
if I am to do a "*y on the previous line in the neovim-dot-app, I will get
¬©
it works correctly when do the yank from within the console nvim. 
So I figure the bug should be filed here. 

neovim-do-app : version
NVIM 0.1.3
Build type RelWithDebInfo

console neovim : version
NVIM 0.1.4-dev
Build type: Dev

**Comment by ivalkeen** [comment]
I have a problem that is probably related but with cyrillic letters. E.g. if I copy this text "Привет" from neovim-dot-app and paste here, I will get this "–ü—Ä–∏–≤–µ—Ç". Both console neovim and macvim work well.

OS: OS X El Capitan (10.11.4)
neovim-dot-app: 0.1.3
neovim: 0.1.3

**Comment by rogual** [comment]
Closing in favour of https://github.com/rogual/neovim-dot-app/issues/120
