### ISSUE TITLE
Meta key support

### ISSUE THREAD

**Issue by nrontsis** [rogual/neovim-dot-app#249]
When I press option and then a letter I get some symbol instead of maps that may be defined. MacVim solves this issue by the `macmeta` option (original discussion about `macmeta` [here](http://vim.1045645.n5.nabble.com/Using-the-option-key-in-MacVim-td1217846.html), similar issue for neovim [here](https://github.com/neovim/neovim/issues/3727)).

Would it be possible/made sense to have a similar option?

Thanks a bunch,

Nikitas

**Comment by bambu** [comment]
This is a repeat of #86. I'll see what I can do with that now that your pr #246 has has been merged. I feel that it should be the option (alt/meta) key that should be implemented and not the command key as requested by the original post.

**Comment by nrontsis** [comment]
Sorry for the repeat! I should have searched before posting.
I agree that the key should be the option (alt/meta) one.

Thanks!

**Comment by bambu** [comment]
Got a working Macmeta option on pr #250. Let me know how it goes.
