### ISSUE TITLE
Neovim-dot-app has window title only

### ISSUE THREAD

**Issue by khalidchawtany** [rogual/neovim-dot-app#252]
I am facing a very strange issue. My neovim-dot-app shows a window title only. I cannot change the height of the window. Even if I make it full-screen, just a title is shown for a second then it switches back to the other desktop. I can resize the desktop horizontally. However, I cannot make any vertical change to the window size. I can see window title change as I edit files and I can enter commands. So, it does work but shows nothing.

 Believe it or not this is all I can see :(
![screen shot 2016-04-28 at 2 29 17 am](https://cloud.githubusercontent.com/assets/1681606/14871236/10e2cd5c-0ce9-11e6-8422-e344ac1be840.png)

Note:
I am using the latest version (--HEAD) of neovim and neovim-dot-app.

**Comment by jrolfs** [comment]
Have you taken a loot at https://github.com/rogual/neovim-dot-app/issues/203? That solved this problem for me.

**Comment by khalidchawtany** [comment]
@jrolfs thank you very much. You made my day :)
