### ISSUE TITLE
Error installing docs with homebrew-version

### ISSUE THREAD

**Issue by bambu** [rogual/neovim-dot-app#253]
I get the following error when installing the homebrew version with `brew install neovim-dot-app --HEAD`:

```
Install directory: "/proj/git/neovim/build/runtime" as "build/Neovim.app/Contents/Resources/runtime"
scons: *** [build/Neovim.app/Contents/Resources/runtime/doc] /proj/git/neovim-dot-app/build/Neovim.app/Contents/Resources/runtime/doc: File exists
```
After some testing I was also able to reproduce this by:
```
make clean
make -j 4 NVIM=../neovim/build/bin/nvim  VIM=../neovim/build/
```
Where `../neovim/build/` is the latest commit (c6594d73c)

**Comment by mjcdiggity** [comment]
+1

I also ran across this same error when trying to compile from source, not surprising though as it should be the same thing as `brew install neovim-dot-app --HEAD`.

**Comment by SuperBo** [comment]
I got this error too

**Comment by scwood** [comment]
Also getting this error.

**Comment by rogual** [comment]
Should be fixed with https://github.com/rogual/neovim-dot-app/commit/82b83845a131ea19dd86d9d018cebec4df7b4fc6

**Comment by bambu** [comment]
Verified working both from source and homebrew
