### ISSUE TITLE
gnvim doesn't source the shell profile?

### ISSUE THREAD

**Issue by liweijian** [rogual/neovim-dot-app#259]
I use neovim to edit OCaml source code, in order to use [merlin](https://github.com/the-lambda-church/merlin), I added the command in my fish shell configure file:
> eval (opam config env)

It works well when I use `nvim` in terminal, but when I tried to open an OCaml file by `gnvim`, it seems that gnvim does not source my profile.

I used to use [mvim](https://github.com/b4winckler/macvim/blob/fd916f58a3723000b9d7b2e0d5657d050e4af962/src/MacVim/mvim), and it works well with my shell profile.

**Comment by rogual** [comment]
Just merged some shell/env fixes — try now?

**Comment by liweijian** [comment]
wow~ it works!
