### ISSUE TITLE
Dead keys support

### ISSUE THREAD

**Issue by rogual** [rogual/neovim-dot-app#26]
`Alt-e e` should give é like in the rest of the OS.

**Comment by josephholsten** [comment]
@rogual any thoughts on how I could try to fix this?

**Comment by rogual** [comment]
We'd have to implement `NSTextInputClient`. Basically, OSX expects us to keep track of some state (the incomplete character being entered), show it to the user, and accept requests from the OS to change that state. Then the OS handles key events itself and manipulates our `NSTextInputClient`, giving us full characters & telling us what partial characters (the 'marked text', as it calls it) to draw.

I did some experiments with this on the `ime` branch — if you look at the latest commit on that branch you should see the basics of how it should work.

**Comment by bambu** [comment]
I think we can close this in favor of #151 as dead key support now exists.
