### ISSUE TITLE
Horizontal mouse scrolling is in the wrong direction

### ISSUE THREAD

**Issue by PixelPirate** [rogual/neovim-dot-app#263]
Scrolling up/down with a mouse wheel or trackpad is "correct", meaning moving the fingers up also moves the content up.

But scrolling left/right is wrong, moving the finger to the right should scroll the content to the right, but it is instead scrolled to the left.

Mixing both scrolling styles together is very annoying, and horizontal scrolling should also adopt the natural scrolling style of vertical scrolling.

**Comment by bambu** [comment]
PR #251 just waiting for it to get merged
