### ISSUE TITLE
Font Antialiasing

### ISSUE THREAD

**Issue by ViViDboarder** [rogual/neovim-dot-app#27]
Your screenshots look like they are cleaner, but when I look at Neovim.app vs MacVim.app with the same font selected, the Neovim ones look far more "fuzzy" like they are antialiased. Is that something that can be disabled?

**Comment by rogual** [comment]
Is it the same problem as https://github.com/rogual/neovim-dot-app/issues/9 ? If not, could you post a screenshot?

**Comment by rogual** [comment]
I have merged some rendering changes — please check if these fix the issue.

**Comment by ViViDboarder** [comment]
:+1: Totally worked! Thanks @rogual.
