### ISSUE TITLE
Only blank window shown when launching

### ISSUE THREAD

**Issue by ckybonist** [rogual/neovim-dot-app#288]
### I got a blank window like this:

![2016-08-18 00 15 32](https://cloud.githubusercontent.com/assets/3832925/17744124/f1a78a48-64d8-11e6-8292-6289c6d2255a.png)
### Version:

```
OS: EI Capitan 10.11.6
neovim: 0.1.4
neovim-dot-app: rogual/neovim-dot-app/neovim-dot-app: stable 0.1.4, HEAD
```
### I follow these steps to install:

```
1. brew tap rogual/neovim-dot-app
2. export VIM="/usr/local/bin/nvim" && brew install neovim-dot-app --HEAD
3. brew linkapps neovim-dot-app
```

**Comment by kamilc** [comment]
Same here

**Comment by bambu** [comment]
Here are a few things you can try do to troubleshoot:

* Can you launch nvim from terminal? Does it prompt you for anything on launch (from terminal)?
* What happens when you press enter or any key?
* Are there any messages in the console?
* What happens when you launch Neovim from terminal with: `/Applications/Neovim.app/Contents/MacOS/Neovim`
* Any messages in terminal when launching it

**Comment by ckybonist** [comment]
- Can you launch nvim from terminal? Does it prompt you for anything on launch (from terminal)?

   **Totally okay**.

- What happens when you press enter or any key?

   **After I pressed enter, It change to normal neovim window.**

- Are there any messages in the console? 

   **The _console in neovim_ keep warning `g:deoplete#sources not defined` if I press any key, while in original nvim this error is not happned.**

- Starting Neovim from terminal: 
   
   **Same situation as Item 2.**

- Any messages in terminal when launching it:

   **Neovim prints `Unknown note >` in terminal after I pressed enter.**

**Comment by bambu** [comment]
Thanks for following up. Does it load properly when you don't load Deoplete? It sounds like Deoplete might be prompting or sending a message which is hanging things up. On the good side, sounds like pressing enter makes it work.

I think i know what the problem is. I'll try to work on it tonight

**Comment by ckybonist** [comment]
Neovim run properly if I don't load deoplete, however, I found other problems:

- It prints these messages to console:

  ```
  Unknown note �� ��
  Unknown note <CR><C
  ```

- _UpdateRemotePlugin_ in Neovim not found.

- Syntax highlighting not activate.
