### ISSUE TITLE
NSCompositeDifference unknown identifier.

### ISSUE THREAD

**Issue by Carreau** [rogual/neovim-dot-app#29]
seeing the [following block](https://github.com/rogual/neovim-dot-app/blob/3fdcec12b6225da3a3bf78b554fbfd9d8816bc2c/src/view.mm#L190-L212) I suppose that NSCompositeDiff is 10.10+ only, though it seem to raise 
```
src/view.mm:199:44: error: use of undeclared identifier 'NSCompositeDifference'
        NSRectFillUsingOperation(viewRect, NSCompositeDifference);
```

On 10.9.5.

**Comment by pjrt** [comment]
Yeah, getting this too on 10.9.3

**Comment by justmytwospence** [comment]
+1

**Comment by rogual** [comment]
Had a go at fixing this in 3cdc927. Did it work?

**Comment by justmytwospence** [comment]
yep!

**Comment by rogual** [comment]
Cool beans.
