### ISSUE TITLE
Build fails with Homebrew: no matching member function for call to 'next'

### ISSUE THREAD

**Issue by mhartington** [rogual/neovim-dot-app#290]
Hi there! So I know macOS 10.12 is still in beta and not publicly out, but I thought I'd give you a heads up!

Trying to install via homebrew fails to build

```bash
$ brew install neovim-dot-app
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
==> Installing neovim-dot-app from rogual/neovim-dot-app
==> Downloading https://github.com/rogual/neovim-dot-app/archive/0.1.4.tar.gz
Already downloaded: /Users/mhartington/Library/Caches/Homebrew/neovim-dot-app-0.1.4.tar.gz
tput: unknown terminal "xterm-256color-italic"
==> make NVIM=/usr/local/opt/neovim/bin/nvim
Last 15 lines from /Users/mhartington/Library/Logs/Homebrew/neovim-dot-app/01.make:
VIM=/usr/local/Cellar/neovim/HEAD/share/nvim NVIM=/usr/local/opt/neovim/bin/nvim scons -Q
Install file: "res/Info.plist" as "build/Neovim.app/Contents/Info.plist"
clang++ -o build/client.o -c -std=c++11 -stdlib=libc++ -g -Wno-deprecated-register -I/usr/local/Cellar/msgpack/2.0.0/include -Ibuild -Isrc src/client.cc
src/client.cc:48:20: error: no matching member function for call to 'next'
    while(unpacker.next(&unpacked)) {
          ~~~~~~~~~^~~~
/usr/local/Cellar/msgpack/2.0.0/include/msgpack/v2/unpack.hpp:1335:23: note: candidate function not viable: no known conversion from 'msgpack::unpacked *' (aka 'msgpack::v1::object_handle *') to 'msgpack::object_handle &' for 1st argument; remove &
inline bool unpacker::next(msgpack::object_handle& result) {
                      ^
/usr/local/Cellar/msgpack/2.0.0/include/msgpack/v2/unpack.hpp:1320:23: note: candidate function not viable: requires 2 arguments, but 1 was provided
inline bool unpacker::next(msgpack::object_handle& result, bool& referenced) {
                      ^
1 error generated.
scons: *** [build/client.o] Error 1
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/rogual/homebrew-neovim-dot-app/issues

Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
```

Now, I'm not sure if this is an error related to you, msgpack, or scons, but thought I'd bring it to your attention.

let me know if you need anymore information.

Cheers!

**Comment by bambu** [comment]
Try 
```
brew install --HEAD neovim-dot-app
```

**Comment by mhartington** [comment]
Hmm, that seems to introduce even more interesting problems. 

The window controls are there, but nothing else.

![screen shot 2016-08-20 at 6 41 22 pm](https://cloud.githubusercontent.com/assets/2835826/17834268/06e7fe90-6706-11e6-8cdc-bbdc72b5a2b6.png)

**Comment by bambu** [comment]
Try `defaults delete uk.foon.neovim` and reboot. Not sure which one of those two actually fixed the issue for people in #203.

**Comment by mhartington** [comment]
Hmm...

```
Domain (uk.foon.neovim) not found.
Defaults have not been changed.
```

After a reboot, same thing.

**Comment by jomuller** [comment]
My two cents: I had exactly the same errors message about *msgpack* under OSX 10.11.6 (fresh Homebrew install). `brew install --HEAD neovim-dot-appbrew install --HEAD neovim-dot-app` fixed the problem. Maybe this bug is not OSX Sierra specific ?

**Comment by mhartington** [comment]
sadly still nothing. Even uninstalling everything, clearing cache, checking defaults and pulling from `--HEAD`, I still get the same window-less window (if that makes sense)

Is there anymore info I could provide? Not sure what else I can give, but happy to help out some how

**Comment by bambu** [comment]
Yeah. Neither of the bugs mentioned are Sierra specific. other people have reported them. 

* Are the maximize / minimize buttons grey even when Neovim.app has focus? If not then what happens when you maximize it or try to resize the window?
* Is nvim running? You can check with `ps awux | egrep -i "(neovim|nvim)"` in your terminal when Neovim.app is running.
* Are any messages being reported in Console for Neovim.app?

I'm not sure what else you can try. Any ideas @rogual? The next thing that I personally would do is to put in some print statements in the code or load it in lldb and actually debug it.

**Comment by mhartington** [comment]
1) Yeah I'm able to maximize/minimize the toolbar, but only it resizes. When I try to toggle full screen, I'll get a full blank screen but nothing there.

2) Yep, neovim is acutally running

```
mhartington     20681   0.0  0.1  2477548  14276   ??  S     7:31AM   0:00.68 nvim --embed
mhartington     20665   0.0  0.2  2852660  39020   ??  S     7:31AM   0:00.99 /usr/local/Cellar/neovim-dot-app/HEAD-68cf699/Neovim.app/Contents/MacOS/Neovim --cwd /Users/mhartington
```

3) I cannot see any console messages from neovim.app

**Comment by leepa** [comment]
I have this same compilation issue on 10.11.6 - so this is not 10.12  specific.

**Comment by rogual** [comment]
I've released 0.1.5, with the Msgpack 2.0 compatibility fixes, so Homebrew should now use that when you `brew install` & everything should be OK again.

Hey @leepa, small world :)

**Comment by rogual** [comment]
Let's keep one issue to an issue, please. This issue is about the compilation failure — please open a new one if you're having other problems.

**Comment by mhartington** [comment]
Compilation looks good now. Now on to my no-gui issue (aka  #203)
