### ISSUE TITLE
gnvim <file> does not open file

### ISSUE THREAD

**Issue by bobzoller** [rogual/neovim-dot-app#296]
to repo:
* brew update && brew upgrade neovim-dot-app # I'm on HEAD-68cf699
* Neovim is not running
* `$ gnvim foobar`
* expected: neovim opens to `foobar`
* actual: neovim opens to scratch buffer

to fix: in gnvim helper, the command that ultimately gets run is: 
`open -a Neovim foobar --args --cwd /Users/bob`

if I move `foobar` into `--args`, it works as expected:
`open -a Neovim --args foobar --cwd /Users/bob`

if this sounds like the correct fix and I'm not missing something, I'm happy to submit a PR.

**Comment by bobzoller** [comment]
`$ gnvim -- Dockerfile` also works as expected, and yields:
`open -n -a Neovim --args --cwd /Users/bob/Projects/ecru Dockerfile`

oh, OSX 10.11.3

**Comment by bobzoller** [comment]
so one workaround is to add `alias gnvim='gnvim -- "$@"'` to your .bashrc or equivalent.

**Comment by bambu** [comment]
Try changing `mode` from `old` to `new`
https://github.com/rogual/neovim-dot-app/blob/master/gnvim#L10

**Comment by bobzoller** [comment]
duh, staring me right in the face.  what's the story, is this an OSX version difference?

**Comment by bambu** [comment]
I can't really tell why that is there. I believe it should be just the `new` way. That is the way that the atom editor does it. I asked about it in #275.

**Comment by bobzoller** [comment]
closing, #275 covers it.
