### ISSUE TITLE
Brew linkapps step broken

### ISSUE THREAD

**Issue by jpedrick** [rogual/neovim-dot-app#315]
$ brew linkapps neovim-dot-app
Warning: `brew linkapps` has been deprecated and will eventually be removed!

Unfortunately `brew linkapps` cannot behave nicely with e.g. Spotlight using
either aliases or symlinks and Homebrew formulae do not build "proper" `.app`
bundles that can be relocated. Instead, please consider using `brew cask` and
migrate formulae using `.app`s to casks.
Error: No such keg: /usr/local/Cellar/neovim-dot-app

**Comment by michel-slm** [comment]
+1. I use mostly Quicksilver which obviates that problem, but a cask still sounds like a better solution.

**Comment by basilesimon** [comment]
Just link it manually:

`ln -s /usr/local/opt/neovim-dot-app /Applications`

**Comment by basilesimon** [comment]
I've filed a PR to fix this issue: https://github.com/rogual/neovim-dot-app/pull/316

**Comment by anticitizen4** [comment]
Better way to link to an `.app` in the Cellar is to use alias (cmd+alt+drag). Spotlight doesn't show symlinks in GUI, it does show aliases though.
[reference](https://apple.stackexchange.com/questions/95906/does-spotlight-normally-index-links-in-applications)

**Comment by sedeki** [comment]
I did this:
```bash
ln -s /usr/local/opt/neovim-dot-app /Applications
```
But I see no Neovim executable in Launchpad, or anything about it in Spotlight.

The easiest solution would be if there was a downloadable .dmg that you could install normally.
