### ISSUE TITLE
use no color scheme?

### ISSUE THREAD

**Issue by kswope** [rogual/neovim-dot-app#317]
As weird as it sounds I put my colorscheme in my init.vim file at the bottom, and this works great for nvim in the terminal, but doesn't work at all in neovim-dot-app because it forces a color scheme upon me.  Is there a way to select no color scheme?

**Comment by kswope** [comment]
I solved my problem by being completely thorough

lots of lines like:

```
hi Operator        ctermfg=none    ctermbg=none    cterm=none    guifg=none    guibg=none
```

But maybe it would be a good feature to offer a null color scheme?

**Comment by rogual** [comment]
Neovim.app shouldn't mess with your colour scheme by default. This is the only VimScript it runs: https://github.com/rogual/neovim-dot-app/blob/master/res/nvimrc — nothing to do with colour schemes in there.

Maybe another scheme is being loaded from elsewhere on your system, or by a plugin?

**Comment by kswope** [comment]
I'm not sure if you can say that neovim.app doesn't mess with your color scheme when there's a menu for colorschemes with no "none" setting.  The menu doesn't seem to be working for me now, no checkmarks besides choices, so maybe somehow I got what I wanted, but someday I see that behavior being fixed.  The question is will the colorscheme be applied before my  $MYVIMRC is run or after.

**Comment by rogual** [comment]
That menu isn't added by NeoVim.app — it simply uses Vim's `:menu` feature and displays whatever menus are present in the Mac menu bar.

**Comment by kswope** [comment]
> That menu isn't added by Neovim.app — it simply uses Vim's :menu feature and displays whatever menus are present in the Mac menu bar.

So what are the implications of this?  Does it do anything?

**Comment by rogual** [comment]
Sorry, not sure what you mean?

**Comment by kswope** [comment]
Is it supposed to do something?  Seems like a dead menu, doesn't do anything, and can't select anything.

**Comment by rogual** [comment]
Works for me. Are you seeing the same theme menu I do?

<img width="391" alt="screen shot 2017-02-24 at 15 12 25" src="https://cloud.githubusercontent.com/assets/520855/23308643/b9cbbd86-faa3-11e6-8ffc-487affe00dbe.png">

Does the menu work for you if you use it with `:emenu`? How about in the terminal?

(To try it, do something like `:emenu Themes.Default.Blue`)

**Comment by kswope** [comment]
You can see nothing is selected.  Actually nothing is select in any of my menus.  If I try to select anything it doesn't stick.  This is Sierra, version 10.12.3, which at this time seems up to date.

![screen shot 2017-02-24 at 10 30 43 am](https://cloud.githubusercontent.com/assets/321586/23309367/6a43258c-fa7c-11e6-9a06-4ed1c1368348.png)

**Comment by rogual** [comment]
If you're expecting checkmarks on menu items, we haven't implemented that. I'm not sure if upstream supports it yet.

As for the colour scheme menu, I've just checked and that also works on my machine. Does your colour scheme not change when you use the menu?

Can you activate it with `:emenu`? For example, `:emenu Edit.Color\ Scheme.blue`?

**Comment by kswope** [comment]
Yes the color schemes work, I think we've been talking paste each other.  Well, they work when I take all my highlight directives out of my $MYVIMRC

I'll attach my init.vim in case you want to see what I'm actually up to.
[init.vim.txt](https://github.com/rogual/neovim-dot-app/files/799978/init.vim.txt)

Going back to the beginning, I was wondering if there was a "none" color-scheme so that I wouldn't have to use all the highlighting directives.  

The command line nvim doesn't *force* a color-scheme like neovim.app , so I only needed a few directives to get the result I wanted.

I share the same init.vim between OSX and a chromebook.

**Comment by wspurgin** [comment]
@kswope This is just a graphical overlay over nvim (which inherit's it's "default" syntax highlighting from vim). If you look at the runtime, the default color scheme is defined there. For me (and for most using this app), it should be located here:

```
/usr/local/share/nvim/runtime/syntax/syncolor.vim
```

That is as close to a "none" as nvim (or vim for that matter) has. As you noted, colorschemes have two definitions. One for `term` and one for `gui`. This app defines itself to nvim as a `gui` app, so if your colorscheme doesn't define the colors for `gui`, then the defaults will be used which are defined in that file above.

So there's no "forcing" of a colorscheme by this app. That's just how vim colorschemes are defined, if you want to use the color scheme in a gui version, you have to define the gui colorscheme elements for it. If you look at [this popular colorscheme you can see they define a function](https://github.com/junegunn/seoul256.vim/blob/master/colors/seoul256.vim#L183-L193) to automatically create their colorscheme definitions for both terminal and GUI elements. That way they don't have to repeat themselves. Might be worth investigating if you want define your own custom colorscheme.
