### ISSUE TITLE
not english input method not work in neovim

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [rogual/neovim-dot-app#320]
hi, i'm a Chinese user, and my Chinese input method is not work，but it shows Chinese very well.  neovim in terminal works fine.

**Comment by FinallyFinancialFreedom** [comment]
ok i find there is a ime branch, when did you merge it to master?

**Comment by asins** [comment]
你是如何解决中文无法输入问题的，我使用的是清歌输入法，同样遇到无法输入的问题。

**Comment by FinallyFinancialFreedom** [comment]
没解决啊，不过我中文输入需求不强，另外，有个ime branch支持输入法，但brew install又不能install分支，等着作者merge到master再说吧
