### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by fungl164** [rogual/neovim-dot-app#323]

**Comment by imizaac** [comment]
I'm also wondering this

**Comment by fungl164** [comment]
For those of you wondering, I found another project that seems to be more active as of now.  Check out http://vimr.org.

**Comment by rogual** [comment]
Active-ish. I use it myself, and it does everything I need, but there are a fair few people having issues which I don't have, and I haven't been taking it upon myself to fix them, although PRs are still most welcome. And I do need to make sure we're up to speed with the latest Homebrew, which is something of a moving target.
