### ISSUE TITLE
Tabline is different in the gui 

### ISSUE THREAD

**Issue by Sydney-o9** [rogual/neovim-dot-app#328]
This is a great GUI for `neovim`, is this still under development?

I have noticed the tabs in the GUI are very different from the ones in the terminal

#### neovim.app

![image](https://user-images.githubusercontent.com/1480617/33464293-a3d76a9c-d695-11e7-96df-71fcb574a4a8.png)

#### iterm2

![image](https://user-images.githubusercontent.com/1480617/33464333-d80639e2-d695-11e7-8c5e-378f9c54403e.png)

Any ideas why `neovim.app` changes the `tabline`

**Comment by rogual** [comment]
Do you mean that the line under the tabs is missing? Looks like the underline-style isn't being applied. We do support underline, so maybe Tabline is trying to check if we support it and getting the wrong answer somehow.
