### ISSUE TITLE
Typo in sysinit.vim "Split Diff with..."

### ISSUE THREAD

**Issue by Roguelazer** [rogual/neovim-dot-app#336]
0.1.5 (the latest release in Homebrew) fails to launch with

```
Error detected while processing /usr/local/Cellar/neovim-dot-app/0.1.5/Neovim.app/Contents/Resources/sysinit.vim:
line 115:
E329: No menu "Split Diff with..."
```

Changing `"with"` to `"With"` fixes this.

This may be a recent incompatibility since I'm running `neovim` 0.3.4, a rather newer version than the 0.1.5 that this was developed against.

Aside from that typo, everything else seems to still work, though, which is kind of neat.

**Comment by rogual** [comment]
Fixed by @bfulkers
