### ISSUE TITLE
Mouse scroll wheel broken

### ISSUE THREAD

**Issue by jocelynmallon** [rogual/neovim-dot-app#34]
It seems the click-count patches to enable double/triple/etc. click events broke mouse wheel scrolling.

You can verify that scrolling worked fine prior by resetting to commit ce1b99c126a7bfbd748fec403068470af2c87a11

**Comment by bulkan** [comment]
Yep it's stopped working and this is output when you scroll 

https://gist.github.com/bulkan/16359a7dabd62af4b119
