### ISSUE TITLE
Pasting while entering a command pastes into the window

### ISSUE THREAD

**Issue by james2doyle** [rogual/neovim-dot-app#39]
![paste-issue](https://cloud.githubusercontent.com/assets/1425304/6993099/a7cec636-dab7-11e4-9f47-647ba68753fc.gif)

I have the link in my clipboard, but when I paste it doesn't paste into the command area, it pastes inline in my window.

**Comment by khalidchawtany** [comment]
I have the same problem. I am on OS X.

**Comment by rogual** [comment]
Confirmed.

**Comment by rogual** [comment]
Fixed in 1897afeb9c35a17c354e9e464fe6e3d2b31408af.

**Comment by james2doyle** [comment]
Nice work!

**Comment by shemerey** [comment]
It looks like issue still here,  it was fixed but on latest build I can't paste anything into command line area, it's just blinking in application menu on `Paste` item
