### ISSUE TITLE
Font line-height not being respected?

### ISSUE THREAD

**Issue by bugeats** [rogual/neovim-dot-app#4]
It appears the font is being rendered with extra line margins. The result is rows that are taller than they should be. 

On the left is NeoVim.app, and on the right is iTerm2. Both are configured (independent of `guifont`) to use DroidSansMono. 

![screen shot 2015-03-26 at 7 35 57 am](https://cloud.githubusercontent.com/assets/33055/6848502/cfeb409c-d38a-11e4-936f-d9ffe3d490b3.png)

As you can see the line height in NeoVim.app is awkward looking.

**Comment by rogual** [comment]
I'll see what iTerm2 does when I get time.

If anyone wants to take a look at this, the character cell size is calculated in `updateCharSize` in view.mm.

**Comment by kopischke** [comment]
Ping on this. The effect is even more awkward with some other fonts, like Menlo for Powerline – see my screenshots in #9 or #49 for examples.

**Comment by bugeats** [comment]
I looked into `updateCharSize` back before the rendering refactor. I couldn't figure out what's going on, but I suspect it's simply that the default font height query is lacking some subtle typography logic. I'm cocoa naive. Apple docs are annoying. :/

**Comment by rogual** [comment]
I've had a go at this — what do you think of the rendering in https://github.com/rogual/neovim-dot-app/pull/58?

**Comment by bugeats** [comment]
I just took a look at #58 and it's now doing what I expect. Attached is a side-by-side with iTerm2 (on the right) using the same nvimrc. Looks like the cell heights are the exact same to me.

![screen shot 2015-04-09 at 4 13 58 pm](https://cloud.githubusercontent.com/assets/33055/7078983/c4731858-ded3-11e4-874b-dc895977f7b1.png)

**Comment by bugeats** [comment]
Since I was scrutinizing the fonts, I did notice that the cursor box offset might also have some rounding issues.

![screen shot 2015-04-09 at 4 06 31 pm](https://cloud.githubusercontent.com/assets/33055/7079015/15a480f4-ded4-11e4-8a11-895249a94c5f.png)

Notice the pokey bit of the "V".

**Comment by kopischke** [comment]
#58 greatly improves things on the line height front. Now for a way to set line spacing (`linespace` is a no-op in the GUI) :).

**Comment by rogual** [comment]
Cool beans, closing this. If those other two things could be separate issues, that'd be grand.

**Comment by kopischke** [comment]
Added #59 for the line spacing.
