### ISSUE TITLE
Case sensitive file system

### ISSUE THREAD

**Issue by libc** [rogual/neovim-dot-app#41]
It doesn't compile out of the box on a case-sensitive file system. The fix is too easy (to create a pull request):

```diff
diff --git a/SConstruct b/SConstruct
index 396ab6c..d0cfc48 100644
--- a/SConstruct
+++ b/SConstruct
@@ -62,6 +62,6 @@ else:
 
 env.Command(
     'build/Neovim.app/Contents/Resources/Neovim.icns',
-    'res/Neovim.png',
+    'res/NeoVim.png',
     'sh makeicons.sh $TARGET $SOURCE'
 )
```

**Comment by rogual** [comment]
618448004bc4a561745efc5652b23f462897078a — Decided to rename the file instead, since the Neovim folks have decided on lowercase 'v'.
