### ISSUE TITLE
Text stays same pixel size when moving between retina and non-retina displays

### ISSUE THREAD

**Issue by selfsimilar** [rogual/neovim-dot-app#42]
![neovim dot app - non-retina to retina](https://cloud.githubusercontent.com/assets/784446/7009039/2b88c6d8-dc5d-11e4-858d-b989fae8079c.png)
Above is a screenshot of a window that was opened on a non-retina display and moved to a retina display.

![neovim dot app - retina to non-retina](https://cloud.githubusercontent.com/assets/784446/7009045/309c7f20-dc5d-11e4-8edb-e5c0a56c107e.png)
Above is a screenshot of a window that was opened on a retina display and moved to a non-retina display.

In both cases the cursor behaves correctly for the resized window, but all text is incorrectly sized,

**Comment by Stiivi** [comment]
Experiencing similar issue. Attached is a result of viewing a file on retina display opened from terminal on non-retina display and scrolling down with keyboard. Note that the font size decreases. Also the view does not seem to fill the whole window. When app is opened on retina display it looks ok.
![screen shot 2015-04-06 at 2 20 33 pm](https://cloud.githubusercontent.com/assets/71105/7009482/8a4c317c-dc68-11e4-9242-3daea805e599.png)

**Comment by rogual** [comment]
Fixed in c9130f6f5873c774d09417fa23892503925f62ef.
