### ISSUE TITLE
Cmd key mapping doesn't work 

### ISSUE THREAD

**Issue by shemerey** [rogual/neovim-dot-app#44]
this is a feature request in order to support `Cmd` key 
for instance, now  

```vim
nnoremap <D-r> :echo('run')<cr> 
``` 
just don't do anything.

**Comment by rogual** [comment]
Fixed in https://github.com/rogual/neovim-dot-app/commit/65597269bc10db7a85546501dbe335f6e5f34403. Use `T-` instead of `D-`.

**Comment by shemerey** [comment]
awesome job, thx
