### ISSUE TITLE
<tuple> missing on OS X 10.8.5

### ISSUE THREAD

**Issue by tourn** [rogual/neovim-dot-app#46]
When running make, this happens:

    shandris :: ~/git/neovim-dot-app ‹master*› % make
    VIM=/usr/local/Cellar/neovim/HEAD/share/nvim NVIM=/usr/local/bin/nvim scons -Q
    g++ -o build/client.o -c -std=c++11 -g -Wno-deprecated-register -Ibuild -Isrc src/client.cc
    src/client.cc:2:10: fatal error: 'tuple' file not found
    #include <tuple>
             ^
    1 error generated.
    scons: *** [build/client.o] Error 1
    make: *** [all] Error 2

I don't really know much about c++. I've been googling around and tried the following
* Upgrade all my homebrew packages
* Change ```-std=c++11``` to ```-std=c++0x```
* Use g++ instead of clang
* Change the offending header to ```#include <tr1/tuple.hpp>
* Change the header to ```#include "boost/tuple/tuple.hpp"```
    * That made the error vanish from client.cc, but instead it then happened in /usr/local/include/msgpack/cpp_config.hpp
* Update my XCode and Command Line Tools (although I can't get the newest one on 10.8)

clang --version says ```Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)```
Does that happen because my xcode is too old? Any pointers what I could try next?

**Comment by rogual** [comment]
My clang gives

```$ clang++ --version
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix```

so I'd guess the `<tuple>` header just wasn't supported in 5.1 — is there no way you can install the newer compiler? If not I'll have a look at supporting older toolchains.

**Comment by tourn** [comment]
So i've installed another LLVM via Homebrew -

    $ /usr/local/opt/llvm/bin/clang++ --version
    clang version 3.5.1 (tags/RELEASE_351/final)
    Target: x86_64-apple-darwin12.6.0
    Thread model: posix

Though it is keg-only, so I have to specify the paths myself. I've managed to wrangle with ```SConstruct``` to produce the following:

    $ make
    VIM=/usr/local/Cellar/neovim/HEAD/share/nvim NVIM=/usr/local/bin/nvim scons -Q
    /usr/local/opt/llvm/bin/clang++ -o build/client.o -c -std=c++11 -g -Wno-deprecated-register -I/usr/local/opt/llvm/include -L/usr/local/opt/llvm/lib -Ibuild -Isrc src/client.cc
    clang: warning: argument unused during compilation: '-L/usr/local/opt/llvm/lib'
    src/client.cc:2:10: fatal error: 'tuple' file not found
    #include <tuple>
             ^
    1 error generated.
    scons: *** [build/client.o] Error 1
    make: *** [all] Error 2

I think the LLVM version now more or less matches yours (as yours is based on 3.5). I see that clang ignores the ```-L``` flag, though I have no idea why, and how to change that.

**Comment by rogual** [comment]
Could you try running this command and tell me what you get? I've included the output on my machine after `brew install llvm --with-clang` for reference:

    $ /usr/local/opt/llvm/bin/clang++ -E -x c++ - -v < /dev/null
    clang version 3.5.1 (tags/RELEASE_351/final)
    Target: x86_64-apple-darwin14.1.0
    Thread model: posix
    "/usr/local/Cellar/llvm/3.5.1/bin/clang" -cc1 -triple x86_64-apple-macosx10.10.0 -E -disable-free -main-file-name - -mrelocation-model pic -pic-level 2 -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu core2 -target-linker-version 241.9 -v -dwarf-column-info -resource-dir /usr/local/Cellar/llvm/3.5.1/bin/../lib/clang/3.5.1 -stdlib=libc++ -fdeprecated-macro -fdebug-compilation-dir /usr/local/opt/llvm -ferror-limit 19 -fmessage-length 147 -stack-protector 1 -mstackrealign -fblocks -fobjc-runtime=macosx-10.10.0 -fencode-extended-block-signature -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o - -x c++ -
    clang -cc1 version 3.5.1 based upon LLVM 3.5.1 default target x86_64-apple-darwin14.1.0
    ignoring nonexistent directory "/usr/include/c++/v1"
    #include "..." search starts here:
    #include <...> search starts here:
    /usr/local/Cellar/llvm/3.5.1/bin/../include/c++/v1
    /usr/local/include
    /usr/local/Cellar/llvm/3.5.1/bin/../lib/clang/3.5.1/include
    /usr/include
    /System/Library/Frameworks (framework directory)
    /Library/Frameworks (framework directory)
    End of search list.
    # 1 "<stdin>"
    # 1 "<built-in>" 1
    # 1 "<built-in>" 3
    # 325 "<built-in>" 3
    # 1 "<command line>" 1
    # 1 "<built-in>" 2
    # 1 "<stdin>" 2

The important part is where it tells you the search path, after `#include <...> search starts here`.

On my system, one of those paths is `/usr/local/Cellar/llvm/3.5.1/bin/../include/c++/v1`, and if I list that directory, the tuple header is there.

Alternatively, maybe your Clang isn't picking up that we're using C++. I had to give `-x c++` above to get that path to be included, whereas Apple's clang just seems to figure it out. You could try adding that flag to CCFLAGS in SConstruct.

**Comment by tourn** [comment]
```
$ /usr/local/opt/llvm/bin/clang++ -E -x c++ - -v < /dev/null
clang version 3.5.1 (tags/RELEASE_351/final)
Target: x86_64-apple-darwin12.6.0
Thread model: posix
 "/usr/local/Cellar/llvm/3.5.1/bin/clang" -cc1 -triple x86_64-apple-macosx10.8.0 -E -disable-free -main-file-name - -mrelocation-model pic -pic-level 2 -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu core2 -target-linker-version 236.4 -v -dwarf-column-info -resource-dir /usr/local/Cellar/llvm/3.5.1/bin/../lib/clang/3.5.1 -fdeprecated-macro -fdebug-compilation-dir /Users/tourn -ferror-limit 19 -fmessage-length 208 -stack-protector 1 -mstackrealign -fblocks -fobjc-runtime=macosx-10.8.0 -fencode-extended-block-signature -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o - -x c++ -
clang -cc1 version 3.5.1 based upon LLVM 3.5.1 default target x86_64-apple-darwin12.6.0
ignoring nonexistent directory "/usr/include/c++/4.2.1/i686-apple-darwin10/x86_64"
ignoring nonexistent directory "/usr/include/c++/4.0.0"
ignoring nonexistent directory "/usr/include/c++/4.0.0/i686-apple-darwin8/"
ignoring nonexistent directory "/usr/include/c++/4.0.0/backward"
#include "..." search starts here:
#include <...> search starts here:
 /usr/include/c++/4.2.1
 /usr/include/c++/4.2.1/backward
 /usr/local/include
 /usr/local/Cellar/llvm/3.5.1/bin/../lib/clang/3.5.1/include
 /usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
# 1 "<stdin>"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 325 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "<stdin>" 2
```

I checked, and I have a `tuple` file in `/usr/local/Cellar/llvm/3.5.1/bin/../include/c++/v1`, though that path is missing from my search path. I've tried sticking that into the `LINKFLAGS`, but to no avail.

**Comment by rogual** [comment]
I don't know why it needs it on yours and not mine, but try adding `-stdlib=libc++` to `CCFLAGS`.

**Comment by tourn** [comment]
Aha! That got me further. Now it crashes a bit later (I cut that out of a huge wall of text, tell me if you need more context): 

```
[...]
clang++ -o build/view.o -c -std=c++11 -g -Wno-deprecated-register -stdlib=libc++ -Ibuild -Isrc src/view.mm
src/view.mm:213:51: warning: 'NSURL' may not respond to 'fileSystemRepresentation'
            const char *path = [[url filePathURL] fileSystemRepresentation];
                                ~~~~~~~~~~~~~~~~~ ^
1 warning generated.
clang++ -o build/Neovim.app/Contents/MacOS/Neovim build/client.o build/process.o build/rpc.o build/vim.o build/app.o build/font.o build/graphics.o build/input.o build/keys.o build/main.o build/menu.o build/redraw.o build/view.o -lmsgpack -framework Cocoa -framework Carbon
Undefined symbols for architecture x86_64:
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::compare(char const*) const", referenced from:
      Vim::wait() in vim.o
      -[AppDelegate notified:withData:] in app.o
  "std::__1::__vector_base_common<true>::__throw_length_error() const", referenced from:
      std::__1::vector<msgpack::v1::object, std::__1::allocator<msgpack::v1::object> >::__append(unsigned long) in client.o
[...]
```

Alternatively, if I change `CPPPATH=['build', '/usr/local/opt/llvm/include/c++/v1', '/usr/local/Cellar/llvm/3.5.1/include/c++/ v1']`, it does this:

```
[...]
clang++ -o build/view.o -c -std=c++11 -g -Wno-deprecated-register -stdlib=libc++ -Ibuild -Isrc -I/usr/local/opt/llvm/include/c++/v1 -I/usr/local/Cellar/llvm/3.5.1/include/c++/v1 src/view.mm
src/view.mm:213:51: warning: 'NSURL' may not respond to 'fileSystemRepresentation'
            const char *path = [[url filePathURL] fileSystemRepresentation];
                                ~~~~~~~~~~~~~~~~~ ^
1 warning generated.
clang++ -o build/Neovim.app/Contents/MacOS/Neovim build/client.o build/process.o build/rpc.o build/vim.o build/app.o build/font.o build/graphics.o build/input.o build/keys.o build/main.o build/menu.o build/redraw.o build/view.o -lmsgpack -framework Cocoa -framework Carbon
Undefined symbols for architecture x86_64:
  "std::__1::locale::use_facet(std::__1::locale::id&) const", referenced from:
      std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in client.o
[...]
```

**Comment by rogual** [comment]
Interesting. Maybe add `-lc++` to `LINKFLAGS`?

**Comment by tourn** [comment]
Yup, that's it. Got it working with

    CCFLAGS=['-std=c++11', '-g', '-Wno-deprecated-register', '-stdlib=libc++'],
    CPPPATH=['build', '/usr/local/opt/llvm/include/c++/v1', '/usr/local/Cellar/llvm/3.5.1/include/c++/v1'],
    LINKFLAGS=['-lc++'],

It compiles and runs. Thanks a lot for your time!

**Comment by rogual** [comment]
No worries. I have added some of these flags to SConstruct on master so future 10.8 users should have an easier time: ac7607a8dd297de15430daaa6da3c8cb533c36ad
