### ISSUE TITLE
"PowerLine" like patched font support 

### ISSUE THREAD

**Issue by shemerey** [rogual/neovim-dot-app#48]
I see another issue with custom patched fonts, if you use custom patched font for "PowerLine", "lightline" or any other plugin, which prettify your `statusline` you can see utf8 chars not displayed properly 

for instance  ![Status Line with patched font](https://www.evernote.com/shard/s3/sh/d7d558bd-30d3-493f-a2db-d1f0c60c4a3d/37ae7ced217e115b107ab4f9f88ce01c/res/f8d4cbf1-44c6-4fba-9e3e-ab60b5e67ad9/skitch.png) 

I use  [Monaco for Powerline](https://gist.github.com/baopham/1838072)  with following setting 
`set guifont=Monaco\ for\ Powerline:h12`

**Comment by rogual** [comment]
Neovim doesn't support `guifont`; try selecting the font using the Font menu instead.

**Comment by shemerey** [comment]
That was my first thought but i can't see this font in font list, might be because it's `User`

**Comment by kopischke** [comment]
@shemerey you are seeing the default Monaco, not your Powerline version. The Powerline version should be pickable from Neovim.app’s font picker no matter where it is installed – **if it is correctly recognised as a fixed width font**. if your Powerline font does not declare this correctly, the picker will not list it.

**Comment by rogual** [comment]
Just had a look at this
* That font you linked has incorrect metadata — does not identify itself as monospaced
* Neovim.app lists only monospaced fonts
* I patched the font for you to fix this bug: https://gist.github.com/rogual/6824790627960fc93077

**Comment by shemerey** [comment]
@rogual thx :+1: I didn't even think about wrong metadata :) now everything is working just fine
