### ISSUE TITLE
No bold fonts used even if available

### ISSUE THREAD

**Issue by kopischke** [rogual/neovim-dot-app#49]
In the below screenshot, using identical configurations, *Neovim.app* displays the “NORMAL” status string in a non-bold weight, while *MacVim* uses the bold weight defined by the status line theme; this can be easily confirmed by inspecting the respective areas with a screen loupe (like xScope):

![neovim app vs macvim](https://cloud.githubusercontent.com/assets/80906/7048704/deffe026-de14-11e4-88ab-7cfb0da6bfc6.png)

– for the record, the Neovim TUI displays the status string in bold without complaining.

*Neovim.app 814cf2bd7ee3f26dde65a2e9eff1396ebc5205cd, OS X 10.10.2, Menlo for Powerline font*

**Comment by rogual** [comment]
Added bold/italic support in 3a31afdf78e014d9247f1b391aaefe0a3aadb305 — should work now.

**Comment by kopischke** [comment]
Very cool!
