### ISSUE TITLE
App exits after a keypress

### ISSUE THREAD

**Issue by vestimir** [rogual/neovim-dot-app#51]
I've compiled it with `NVIM=/usr/local/bin/nvim make`, but when I open the application, the screen is blank (and it's not picking up my nvimrc) and if I press any key it exits.

**Comment by rogual** [comment]
* Try running from the terminal with `build/Neovim.app/Contents/MacOS/Neovim`. Do you get any output on the terminal?

* Try running with a blank .nvimrc

* Is anything interesting being written to `~/.nvimlog`?

* If none of that helps, a traceback would be helpful. Do `lldb build/Neovim.app/Contents/MacOS/Neovim` then `r<enter>`. Do you get any output?

**Comment by hoop33** [comment]
Getting the same issue.
* Try running from the terminal with build/Neovim.app/Contents/MacOS/Neovim. Do you get any output on the terminal?

[0, "Invalid method name"]

* Try running with a blank .nvimrc

Same results

* Is anything interesting being written to ~/.nvimlog?

2015/04/09 09:32:02 [info @ main_loop:561] 27047 - Starting Neovim main loop.
2015/04/09 09:32:02 [error @ msgpack_rpc_call:49] 27047 - Error dispatching msgpack-rpc call: Invalid method name(request: id 0)
2015/04/09 09:32:06 [error @ msgpack_rpc_call:49] 27047 - Error dispatching msgpack-rpc call: Invalid method name(request: id 3)

* If none of that helps, a traceback would be helpful. Do lldb build/Neovim.app/Contents/MacOS/Neovim then r<enter>. Do you get any output?

$ lldb build/Neovim.app/Contents/MacOS/Neovim
(lldb) target create "build/Neovim.app/Contents/MacOS/Neovim"
Current executable set to 'build/Neovim.app/Contents/MacOS/Neovim' (x86_64).
(lldb) r
Process 27332 launched: '/Users/rwarner/Development/neovim-dot-app/build/Neovim.app/Contents/MacOS/Neovim' (x86_64)
(Note: at this point I switched to the NeoVim window and hit ':')
[0, "Invalid method name"]
Process 27332 exited with status = 255 (0x000000ff)
(lldb)

**Comment by rogual** [comment]
Maybe your nvim is too old — what do you get from `nvim --version`? (And does this problem go away if you install the latest?)

**Comment by vestimir** [comment]
For me updating nvim and rebuilding the app bundle fixed the problem :)

**Comment by hoop33** [comment]
Bingo. I had an older version in my path. Same fix for me.
