### ISSUE TITLE
Incorrect scroll after zoom-in/out in full screen

### ISSUE THREAD

**Issue by vestimir** [rogual/neovim-dot-app#52]
Whenever I zoom in with `cmd+` I have to exit and re-enter full screen in order to be able to scroll up to the beginning of the file.

**Comment by rogual** [comment]
Confirmed.

**Comment by rogual** [comment]
Fixed in https://github.com/rogual/neovim-dot-app/commit/25d596b356a4dab7b337245157f07a4d66a03d59.
