### ISSUE TITLE
In a full screen mode changes the font size doesn't change window size

### ISSUE THREAD

**Issue by shemerey** [rogual/neovim-dot-app#56]
Steps to reproduce 

* open full screen 
* `Cmd` + `-` a few times 

You will get something like this 

![Full screen Neovim](https://www.evernote.com/shard/s3/sh/eace8008-9d46-44bc-9848-d04ce79209d1/562cc1765a23057ec6f1de856bb85061/res/389aee94-2a59-44e4-92a5-4db6cead51b2/skitch.png?resizeSmall&width=832)

**Comment by rogual** [comment]
Are you on latest master? This may have been fixed by https://github.com/rogual/neovim-dot-app/commit/25d596b356a4dab7b337245157f07a4d66a03d59.

**Comment by shemerey** [comment]
my mistake, didn't update it . yes it's fixed thx.

**Comment by rogual** [comment]
No worries!
