### ISSUE TITLE
Way to set line spacing

### ISSUE THREAD

**Issue by kopischke** [rogual/neovim-dot-app#59]
As noted in #4, `linespace` is a no-op in the GUI (because it is a no-op in Neovim?). As legibility is both highly subjective and tightly coupled to line spacing and column width, an option to set line spacing in _Neovim.app_ would be helpful..

**Comment by khalidchawtany** [comment]
Is there any update on this? Being able to set some line spacing (line height) improves readability a lot without having to increase font size.

**Comment by maccius** [comment]
I understand that a feature like this isn't a priority, but I will put in another vote for this feature. The inability to set `lsp` is one of the only things keeping me from transitioning fully from MacVim.

**Comment by amk221** [comment]
I'd really like to use this neovim app, but this issue is preventing me from doing that. Would like to know if it will be supported any time soonish? Thanks

**Comment by crypticsymbols** [comment]
I would like to help with this, since it's kind of a show-stopper for me. If someone can point me in the general direction of the relevant parts of the code and maybe brief me on what's been tried so far, I can dedicate some time to it. Love NeoVim so far, I'm super stoked on it!

**Comment by bambu** [comment]
@crypticsymbols,

It likely wont be possible to do `set linespace=4` as that would require the setting being added to neovim proper. You can add a custom call to accomplish it (check `res/nvimrc`, `window.mm`)

As far as code to make the linespacing happen would be modifying:
https://github.com/rogual/neovim-dot-app/blob/master/src/view.mm#L489-L503

In doing so, you will need to take into account that fonts in multiple languages show up properly. You can see a few in https://github.com/rogual/neovim-dot-app/blob/master/src/redraw.mm#L83-L91.
