### ISSUE TITLE
Redraw sluggish

### ISSUE THREAD

**Issue by SirVer** [rogual/neovim-dot-app#6]
First: congrats on the strong start. This project was the first of the many gui projects I actually got up and running without any hickups.

Unfortunately, it is very sluggish in redrawing. Any chance of speeding that up somehow?

**Comment by rogual** [comment]
Hey, thanks for the feedback!

I've recently done one round of redraw optimizations to close this issue — https://github.com/rogual/neovim.app/issues/5 — but I guess there's still room for improvement.

Is everything slow for you? Like, when you're just typing? Or is it when you're scrolling, opening lines, or doing things like `:!ls`?

**Comment by SirVer** [comment]
Yes, everything is rather slow, even just normal typing laggs significantly.

I ran instruments over the binary while banging keys and moving around the buffer in a largish file with my full .vimrc enabled - many plugins. I see that most of the time (55%) of the time in the app is spend in `VimView(redraw) > VimView drawRect`. And the App is maxing out one full CPU.

Is there a way to build the app in release mode? Maybe that makes a performance benefit.

**Comment by rogual** [comment]
If you edit `SConstruct` and change the 0 to a 1 on line 15, you should get a release build.

**Comment by SirVer** [comment]
Worked - I got an optimized build. But it did not make anything faster.

**Comment by rogual** [comment]
Just done a bit more optimization in https://github.com/rogual/neovim-dot-app/commit/d0076cd52f4968884662759e3aa45096a9c3726f. Is it fast for you now, or is more needed?

**Comment by SirVer** [comment]
Now it is buggy. I only see a black screen and the cursor - typing moves the cursor, so the logic seems to work, only the drawing is broken. The cursor moves very quickly while typing though, so it seems that your improvements did improve performance on my system. Screenshot:

![screenshot](http://i.imgur.com/4P3nuLD.png)

**Comment by rogual** [comment]
Damn. Would you just check it isn't a bug in the build script for me?

```
rm -rf build
make
```

If not I'll revert this and we may have to drop down to CoreGraphics.

**Comment by SirVer** [comment]
Done now on f73bfb6864b5157d1a3382026335119324ae1c79. No change, still a black output window.

~~~
$ rm -rf build 
$ git diff 
diff --git a/SConstruct b/SConstruct
index a1986e4..0ff6a90 100644
--- a/SConstruct
+++ b/SConstruct
@@ -12,7 +12,7 @@ env.Append(
     FRAMEWORKS=['Cocoa']
 )

-if 0:
+if 1:
     env.Append(
         CCFLAGS=['-O3', '-DNDEBUG'],
     )
$ make
-- build output skipped
~~~~

**Comment by rogual** [comment]
Thanks for doing that. Other people have been having this problem too (infuriatingly, I haven't) so I've reverted the latest graphics optimization commit. Will try attacking it from a different angle.

**Comment by rogual** [comment]
I've been doing some more optimization work in a separate branch; it's all working for me, but would you be able to check it out and make sure it doesn't bring that blank screen bug back for you?

https://github.com/rogual/neovim-dot-app/pull/30

If it's all good I'll merge it.

**Comment by SirVer** [comment]
it renders okay again - I think it even looks better. But it is still very slow for me. no perceived change in performance actually.

**Comment by rogual** [comment]
That's so weird, it's blazing fast on mine. If you could do Save in the Time Profiler and get the .trace file to me somehow I'd be happy to try and fix it.

**Comment by SirVer** [comment]
I investigated a bit more. This is what I found out: 

1) when i open the prog using `open build/NeoVim.app/Contents/MacOS/NeoVim /tmp/blub.txt`, i.e. with a file it never lags and is very quick.
2) when I open the program without a txt file, it lags a lot. Until I do `:set nolazyredraw`. 
3) Empty vimrc does not lag. 

Can you reproduce any of this?

**Comment by rogual** [comment]
I can't. If it doesn't lag for you with an empty .nvimrc it's probably the interaction of a plugin with Neovim.app — if I knew which one I could install it and debug.

**Comment by SirVer** [comment]
Setting `nolazyredraw` fixes the problem for me, so I'll stick with that. thanks for your help!

**Comment by notsimon** [comment]
I just installed neovim.app and I'm really impressed by what you've already achieved.

Unlike @SirVer, I had slow rendering issues mostly when scrolling or jumping between paragraphs.
`:set nolazyredraw` improved a lot the performances. However I'm not sure that's the best solution we can come up with, maybe this issue should be reopened ?

**Comment by clord** [comment]
`nolazyredraw` seems to help. now the cursor seems more solid (it does not jump). However,  repeating an action stops redrawing until you let go, although once you do it seems the required actions have been performed without GUI feedback. Worse, some commands seem to queue up and then play back slowly until caught up with real-time. Feels like a buffer is in there somewhere causing undue latency. 

Cursor movement should have some latency goal for all possible movements.
