### ISSUE TITLE
Can't input unicode characters

### ISSUE THREAD

**Issue by ianclarksmith** [rogual/neovim-dot-app#63]
Many unicode characters can't be input or even displayed. For example, when I paste `日本語` I see `日本___` (`_` represents blank space). Typing with kotoeri input yields `nihongo` (actual keys pressed), while input from kana table or character viewer don't register anything. In a directory with an existing folder named `日本語` the ls command shows the same as when I attempt to paste (`日本___`). European accents I can paste and display but not type.

This is what happens when I drag-select text that originally read `日本___`:
![screen shot 2015-04-13 at 4 25 30 pm](https://cloud.githubusercontent.com/assets/1631923/7124832/1a52b340-e1fa-11e4-836a-29175fdc3e97.png)

No issues with `nvim` launched from the shell, i.e. I can type, paste, display all unicode characters fine.

**Comment by rogual** [comment]
Thanks for the bug report. Looks like there are a few issues here.

One issue is with double-width characters, which should be fixable but it doesn't surprise me that it exists — Neovim.app doesn't have any logic to handle them at the moment.

Your kotoeri issue will unfortunately have to wait until I educate myself about what Kotoeri is. If it's an IME then this again doesn't surprise me but is definitely something we want to support.

As for your accent troubles: what accents are you trying to type, and what keys are you pressing to type them? Also it would be useful if you could post your keyboard layout and the output from `locale` in the terminal.

**Comment by ianclarksmith** [comment]
```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

(On terminal-locale branch + additional setenv() for LANG)

<kbd>Alt e</kbd><kbd>e</kbd> should input é.
<kbd>Alt u</kbd><kbd>u</kbd> should input ü.

The çedilla works and is input with <kbd>Alt c</kbd>. Other characters which can be input in a non-chorded (Mod+key) sequence work such as ¡™£¢∞§¶•ªº“‘.

Pasting "ümlàüt çédìlle" in insert mode displays `ümlàüt çédìlle` (correct).
Pasting "ümlaut çédille" in normal mode displays `<9f>mlaut <8d><8e>dille`.
(Paste is done with <kbd>Command V</kbd>)

I use the US, Dvorak, and Japanese (apparently in 10.10 references to "Kotoeri" have been dropped) input methods that are built in to OS X.

**Comment by rogual** [comment]
Alt-e and Alt-u are dead keys so are covered by https://github.com/rogual/neovim-dot-app/issues/26.

That pasting bug is weird! All normal-mode paste does is `"+p` which works in terminal Neovim, but in Neovim.app seems to paste in what looks like code page 10029 (http://en.wikipedia.org/wiki/Macintosh_Central_European_encoding).

I'm going to split this into three issues: Double-width character support, pasting bug, and Japanese IME support.
