### ISSUE TITLE
Command-line invocation

### ISSUE THREAD

**Issue by Stiivi** [rogual/neovim-dot-app#65]
It would be nice if NeoVim.app had a command-line invocation in a similar way as `vimr` and `macvim` have. Instead of running `open -a NeoVim ...` do something like `neovimapp ...` or just `neo` (not sure if it would not conflict with some other tool though).

**Comment by shemerey** [comment]
@Stiivi there is a shortcut, you can put following 

```bash
#!/bin/sh
open -a Neovim ${1:+"$@"}
```

some where in /usr/local/bin . For instance  I've put  it into `/usr/local/bin/n` and it works fine for me, but Ii's kind of a trick, you still can't pass any arguments even with `--args` for `open`

**Comment by rogual** [comment]
@shemerey What does that `${1:+"$@"}` notation mean? I've never seen it before.

@Stiivi Would you want such a command to do anything that `open -a Neovim $*` can't do? If not, I'm happy leaving this as something for users to add with an alias or a shell script.

**Comment by Stiivi** [comment]
Thanks, I have it aliased, just suggestion that Neovim.app might provide a way to install a small script in `/usr/local/bin` or append `alias ...` to `.profile` through a button in app preferences in a similar way as other editors are doing it. Eases adoption of the app.

**Comment by rogual** [comment]
It's not a bad idea, but I want to keep Neovim.app as small and light as possible, at least as long as I'm the person doing most of the coding — so I'd prefer to keep the focus on being a text editor and not add features that configure the user's `.profile` and such. Hope that makes sense.
