### ISSUE TITLE
Accept stdin through command-line

### ISSUE THREAD

**Issue by Stiivi** [rogual/neovim-dot-app#66]
Accept stdin to a new buffer (tab/split/... depends on a setting/option) through command line (maybe with #65?). It would be nice if I can do:

```bash
$ git diff | neovimapp
```

and the diff will be opened in a buffer. Vim's `-` argument might be optional.

**Comment by rogual** [comment]
You can do this with `open -f`, e.g.

    git diff | open -fa Neovim

**Comment by Stiivi** [comment]
Thanks, I've aliased it. Not obvious, but works.
