### ISSUE TITLE
Cannot paste while entering commands (:command )

### ISSUE THREAD

**Issue by khalidchawtany** [rogual/neovim-dot-app#71]
Cannot paste while entering commands.

This was working after https://github.com/rogual/neovim-dot-app/commit/1897afeb9c35a17c354e9e464fe6e3d2b31408af was merged. However, this is beoken again :cry:

This issue is different from the issue  "[Pasting while entering a command pastes into the window] (https://github.com/rogual/neovim-dot-app/issues/39)" in that when you press Command+V nothing happens and nothing gets pasted nowhere.

**Comment by rogual** [comment]
Thanks! Fixed in 257a02620f66752182ae69d208fec91f976e268f.

**Comment by khalidchawtany** [comment]
That was super fast :smile: 
I confirm that is working again, Thanks.
