### ISSUE TITLE
Scrolling is slow

### ISSUE THREAD

**Issue by resistor** [rogual/neovim-dot-app#75]
I use a Logitech mouse with an "unlockable" scroll wheel for fast scrolling.  While scrolling works fine in the locked mode, when I unlock to scroll quickly Neovim.app becomes very skippy.

**Comment by rogual** [comment]
What is the model of your mouse?

**Comment by fritzy** [comment]
I have a Logitech mouse with the same feature at my office. I'll try i there and see if I can reproduce for you @rogual. I didn't notice a problem using smooth scrolling with a Mac touchpad though.

**Comment by fritzy** [comment]
Scrolling falls behind @rogal -- seeming to send one scroll at a time when it should be skipping a bit with high speed scrolling.

**Comment by shazow** [comment]
Same here, using a touchpad, looks like there is a max scroll speed so it effectively ignores the acceleration of my "flick" when I scroll. Macvim.app side-by-side will scroll all the way to the bottom with a single swift flick nearly instantly, whereas Neovim.app reaches a maximum scroll speed and keeps scrolling at that rate for a while before stopping. I can record a video if that helps.

**Comment by rogual** [comment]
I'm going to close this in favour of https://github.com/rogual/neovim-dot-app/issues/99 since it's not specifically scrolling that's slow. Fixing the text renderer should also fix scrolling performance.
