### ISSUE TITLE
HOME/END buttons do nothing

### ISSUE THREAD

**Issue by resistor** [rogual/neovim-dot-app#76]
In MacVIM, they take me to the beginning/end of the document respectively.

**Comment by rogual** [comment]
Can you map them?

    nmap <Home> gg
    nmap <End> G

If so, then let's just add these as default mappings in `nvimrc`.

**Comment by gkatsev** [comment]
`Home`, `End`, `PgUp`, and `PgDwn` all work the same for me here as in macvim.

**Comment by rogual** [comment]
Thanks. Going to close this as we haven't heard from OP in a while.
