### ISSUE TITLE
Option to disable bell

### ISSUE THREAD

**Issue by fritzy** [rogual/neovim-dot-app#77]

**Comment by shazow** [comment]
+1, I haven't done any objc but I'd be happy to poke around for this if anyone has some pointers. :)

**Comment by shazow** [comment]
On second thought/investigation, is there any reason that `:set noerrorbells` or `set visualbell t_vb=` is not sufficient?

**Comment by rogual** [comment]
`set visualbell t_vb=` seems to work for me.

**Comment by fritzy** [comment]
good point!
