### ISSUE TITLE
Support windows bigger than 1920x1080

### ISSUE THREAD

**Issue by dcjones** [rogual/neovim-dot-app#80]
I sometimes use a large monitor turned vertically. When maximized neovim.app will clip the top of the screen, drawing only the cursor. It seems like there are a maximum number of rows that it will draw. See screenshot:

![screen shot 2015-04-29 at 10 41 56 am](https://cloud.githubusercontent.com/assets/210361/7397395/de93b092-ee5c-11e4-9a55-f54090825f22.png)

**Comment by gglanzani** [comment]
I got this behavior too (on a 4k monitor)

**Comment by assemnical** [comment]
same problem here when maximizing the window, im on 1920x1200

**Comment by rogual** [comment]
Can confirm. The screen is drawn into a fixed-size buffer and this needs to change.

**Comment by rogual** [comment]
Should be fixed with 73e789b — I don't have a massive screen, so could you check and let me know?
