### ISSUE TITLE
Support 'lines' option

### ISSUE THREAD

**Issue by tkhren** [rogual/neovim-dot-app#81]
How to reproduce

1. Open Neovim
2. `:set lines=XXX`  " XXX is an integer value
3. The command line will fade out

**Comment by dotjairo** [comment]
Resizing the window brings it back. Note that resizing the window changes the value of lines:
* `:echo &lines`
* resize window
* `echo: &lines`

**Comment by tkhren** [comment]
Yes, using mouse, it works correctly. But I'd like to resize on a vim script.
This bug does not only reproduce on Neovim.app but also the terminal neovim.
Would it be better to re-post as an issue into the neovim repo not here?

**Comment by rogual** [comment]
The issue here is that the GUI doesn't adjust itself when `lines` is set. Hopefully Neovim makes it easy for us to detect this.

**Comment by rogual** [comment]
Fixed in https://github.com/rogual/neovim-dot-app/pull/158
