### ISSUE TITLE
homebrew formula

### ISSUE THREAD

**Issue by randy3k** [rogual/neovim-dot-app#82]
I have written a homebrew formula for neovim-dot-app and submitted a PR to https://github.com/neovim/homebrew-neovim/pull/55.

Let's wait the Neovim team's respond. If they don't like it, I think it will be reasonable to put the formula in neovim-dot-app repo. Meanwhile, one can do
```
brew install https://gist.githubusercontent.com/randy3k/39150b24abfb9798db99/raw/c10f30d8cb73324492c4f293d858457a833efd15/neovim-dot-app.rb --HEAD
```

**Comment by cseelus** [comment]
Nice, thx

**Comment by rogual** [comment]
Thanks for this! I'll get this set up soon.

**Comment by kerunaru** [comment]
So, they seems to prefer @rogual to create a [stand-alone repo for nevoid-dot-app](https://github.com/neovim/homebrew-neovim/pull/55#issuecomment-98416497)

**Comment by assemnical** [comment]
Is it possible to specify the python version ? In my case YouCompleteMe is build against another python version.

**Comment by randy3k** [comment]
@assemnical 
just make sure your python is 2.x and now you can install it without python 
```
brew install https://gist.githubusercontent.com/randy3k/39150b24abfb9798db99/raw/c10f30d8cb73324492c4f293d858457a833efd15/neovim-dot-app.rb --HEAD --without-python
```

**Comment by randy3k** [comment]
@rogual 
The formula can be found [here](https://gist.github.com/randy3k/39150b24abfb9798db99).

**Comment by rogual** [comment]
All set up. Thanks a lot for writing the script @randy3k.

Any issues with it, please raise in the new repo's issue tracker.

https://github.com/rogual/homebrew-neovim-dot-app/blob/master/neovim-dot-app.rb
