### ISSUE TITLE
Ability to change ANSI color?

### ISSUE THREAD

**Issue by randy3k** [rogual/neovim-dot-app#83]
I really hate the default ANSI colors in the terminal mode.
Is it possible to change the ANSI colors?

Front: Terminal, Back: Neovim
![screen shot 2015-05-01 at 7 01 13 pm](https://cloud.githubusercontent.com/assets/1690993/7439542/7b814120-f034-11e4-9cd2-cfae954af98f.png)

**Comment by rogual** [comment]
Neovim itself decides which colours to draw, not the GUI, so this would be an issue for the neovim project itself.

**Comment by randy3k** [comment]
IMHO, the colors are printed by the GUI, so the changes should also done by the GUI. In Terminal and iTerms, there are also options to change ANSI colors. In the current implementation, there is an option to change font and font size. I don't see  why the colors should be handled by the backend. Particularly, neovim has separated the frontend interface from the backend engine.

**Comment by BoundInCode** [comment]
Right now, you can change the colors using the following:
```
let g:terminal_color_0  = '#2e3436'
let g:terminal_color_1  = '#cc0000'
let g:terminal_color_2  = '#4e9a06'
let g:terminal_color_3  = '#c4a000'
let g:terminal_color_4  = '#3465a4'
let g:terminal_color_5  = '#75507b'
let g:terminal_color_6  = '#0b939b'
let g:terminal_color_7  = '#d3d7cf'
let g:terminal_color_8  = '#555753'
let g:terminal_color_9  = '#ef2929'
let g:terminal_color_10 = '#8ae234'
let g:terminal_color_11 = '#fce94f'
let g:terminal_color_12 = '#729fcf'
let g:terminal_color_13 = '#ad7fa8'
let g:terminal_color_14 = '#00f5e9'
let g:terminal_color_15 = '#eeeeec'
```
So, the GUI _could_ include a preference pane to set these values. IMO, that's not really necessary though.
(see [this PR](https://github.com/neovim/neovim/pull/2076))

**Comment by randy3k** [comment]
@BoundInCode Thanks for the tips. :+1:
