### ISSUE TITLE
hjkl movement: key repeat not working

### ISSUE THREAD

**Issue by assemnical** [rogual/neovim-dot-app#85]
Keep pressing one of those buttons should keep moving in the direction until the button is released. This is the behavior of vim and nvim. Right now it just stops after one char in the Neovim app.

**Comment by rogual** [comment]
Can't reproduce.

**Comment by assemnical** [comment]
I've build the latest master und replaced my .nvimrc with an empty one but the behavior is still the same. I'm on OS X 10.10.3.
NVIM 0.0.0-alpha+201504281729 (compiled Apr 28 2015 16:39:31)
Commit: a903407471d8b480737d43db1d271c6650580f1c
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20150428-2308-duwbgz/build/config -I/tmp/neovim20150428-2308-duwbgz/src -I/tmp/neovim20150428-2308-duwbgz/.deps/usr/include -I/tmp/neovim20150428-2308-duwbgz/.deps/usr/include -I/tmp/neovim20150428-2308-duwbgz/.deps/usr/include/luajit-2.0 -I/tmp/neovim20150428-2308-duwbgz/.deps/usr/include -I/tmp/neovim20150428-2308-duwbgz/.deps/usr/include -I/tmp/neovim20150428-2308-duwbgz/.deps/usr/include -I/tmp/neovim20150428-2308-duwbgz/.deps/usr/include -I/Library/Frameworks/R.framework/Headers -I/usr/include -I/tmp/neovim20150428-2308-duwbgz/build/src/nvim/auto -I/tmp/neovim20150428-2308-duwbgz/build/include

The nvim behavior in the terminal is working as expected but not wrapped in this app.

**Comment by lagsalot** [comment]
Could this be related to the OS X key repeat / accents behavior?

**Comment by gkatsev** [comment]
I also see this issue. The longer you press the longer it keeps going but it does stop eventually. I see this issue with the arrow keys as well.
Probably buffers a bunch of the key events and doesn't clear the buffer...

I just tried it with `w` and `b` and got the same result.

**Comment by rogual** [comment]
@lagsalot you'd think so, but I have my OSX set to accents rather than repeat and repeat still works for me in Neovim.app

@gkatsev Sounds like you're having a different issue where the key does repeat but keeps repeating after you release it? This issue is about repeat not triggering at all.

**Comment by assemnical** [comment]
@rogual i can debug it if you can tell me how you handle key events.

**Comment by rogual** [comment]
That's a kind offer, thank you!

Key events come in here: https://github.com/rogual/neovim-dot-app/blob/master/src/input.mm#L13

`translateKeyEvent` is called, which generate's Vim's `<xxx>` sequences: https://github.com/rogual/neovim-dot-app/blob/master/src/keys.mm#L148 (note two overloads)

Then the input goes straight to Vim using its `vim_input` RPC: https://github.com/rogual/neovim-dot-app/blob/master/src/input.mm#L85

**Comment by gkatsev** [comment]
@rogual ha, you're right. Totally missed that. Should I create a new issue for that or should we just track it here under a general key repeat problems?

**Comment by rogual** [comment]
I'd prefer that to be a separate issue, yeah.

**Comment by kuglee** [comment]
I have the same issue.
Key repeat was working with 75f71ac.
Key repeat is not working with edd1fc7.

**Comment by josephholsten** [comment]
I can't reproduce. is this still open?

**Comment by rogual** [comment]
Well, we have a lot of people who can't reproduce, and we haven't heard from @assemnical in a while, so let's close it.
