### ISSUE TITLE
Key repeat continues, even after letting go of key

### ISSUE THREAD

**Issue by gkatsev** [rogual/neovim-dot-app#87]
For me, when pressing and holding a key down, the key repeats (unlike #85), however, it continues to repeat even after letting go. The longer the key was held down, the longer it keeps repeating.
This is happening with most keys. Keys I checked specifically are movement keys like `hjkl`, arrow keys, and `w`, and `b`.

**Comment by rogual** [comment]
This sounds like a performance issue (app taking too long to process each key-repeat message)

**Comment by dvcrn** [comment]
Same issue here. Key repeats long after letting go of the key. The higher the repeat interval (mac settings), the longer it continues scrolling. Especially when browsing files with a lot of lines this is a issue since it tends to outscroll when it should stop

**Comment by rogual** [comment]
I'm hoping this will get sorted when we get a faster screen-drawing routine (which should be — the developer's favourite word — “soon”)

**Comment by rogual** [comment]
Some performance fixes have been merged since this was opened — is it still a problem for you guys?
