### ISSUE TITLE
Font selection panel shows an empty list of fonts

### ISSUE THREAD

**Issue by fturcheti** [rogual/neovim-dot-app#92]
I'm having problems with the font selection panel. It should be populated with my monospaced fonts, but I'm facing an empty list:

![screenshot](https://dl.dropboxusercontent.com/u/1279249/neovimdotapp-font-selection.png)

I'm running OS X 10.9.5.

**Comment by rogual** [comment]
Thanks for this.

**Comment by rogual** [comment]
Suggested solution: filter fonts individually rather than by category.

**Comment by rogual** [comment]
Ugh, why does Cocoa make everything so complicated.

So (this is all in `font.mm`):

* We use a custom `NSFontManager` class called `VimFontManager` in an attempt to present only monospaced fonts to the user.

* Apple docs describe a method `willIncludeFont:` but docs warn:
| This delegate method is not called in OS X versions 10.3 and later.

* So, currently we override `collectionNames` and filter out collections that aren't entirely monospaced. Not ideal, but at least that method actually gets called.

* But, users can customize their font collections, so there is no guarantee the "Fixed Width" collection exists or will pass the filter.

**Comment by fturcheti** [comment]
Hey, thank you for the explanation. This made me realize that the problem was in my fonts collection. You are right, there are fonts in my (supposed) monospaced collection that are not true monospaced or, at least, are not correctly specified as so.
As a workaround, I created a new smart collection in Font Book with the filter "Design style is Monospaced" and... voilà! Now I have a font collection that, for sure, works with the filter implemented in Neovim.app. Maybe you should just add instructions about this in the README and close the issue.

**Comment by josephholsten** [comment]
Is there a reason we can only have fixed width fonts? (yes, I'm an old acme user and strange.)

**Comment by rogual** [comment]
Yeah. Basically, Vim deals with a grid of characters and there's no way to change this at the UI level. For instance, when you split a window vertically, Vim will just tell us to draw the `|` characters in all the cells in column 37 or wherever. If we used proportional fonts, the `|` chars for the vertical split wouldn't line up.

It's not like Emacs where the core tells the UI "draw two splits, put this text in this one and that text in the other". The display abstraction in Vim is explicitly character-cell based.

**Comment by bambu** [comment]
@fturcheti can you try  #159 and see if it works for you?

**Comment by fturcheti** [comment]
@bambu it works!
