### ISSUE TITLE
Opening a directory (with nerdtree) fails on cold start

### ISSUE THREAD

**Issue by shazow** [rogual/neovim-dot-app#93]
With the nerdtree plugin, when I open a directory with nvim, I get a nerdtree view. When I open it with Neovim.app, I just get a buffer open with the directory name. When I open it again after Neovim.app is already open (`:e .`), it works.

```
$ nvim .  # Works
$ open -a Neovim.app .  # Does not work
$ open -a MacVim.app .  # Works
```

**Comment by rogual** [comment]
Interesting, thanks!

**Comment by rogual** [comment]
OK, so at the moment, when you specify files on the command line, an `:e FILENAME` command is sent to the first Vim process just after it starts.

Perhaps Vim is handling this before initializing NetRW/NerdTree?

It'd be good to just pass the filenames directly on to `nvim` as command-line arguments, I think, just to ensure consistent behaviour. My guess is that that would fix this issue.

**Comment by dvcrn** [comment]
Giving my +1 here. 
```
alias 'nvin'="open -a /usr/local/opt/neovim-dot-app/Neovim.app"
```

`nvin .` does not open netrw / nerdtree. Only when I mess around with keys (for example manually open nerdtree and close it), it suddenly refreshes and netrw is visible.

**Comment by josephholsten** [comment]
see also #97

**Comment by rogual** [comment]
This might be fixed now.

**Comment by rogual** [comment]
Seems to be fixed.
