### ISSUE TITLE
Horizontal scrolling with trackpad

### ISSUE THREAD

**Issue by shazow** [rogual/neovim-dot-app#94]
When opening a file that has some long lines, MacVim.app will accept horizontal scroll gestures to scroll appropriately, whereas Neovim.app only scrolls vertically with the trackpad.

**Comment by bambu** [comment]
Neovim.app currently sends the horizontal scroll movements to neovim. However, there is no code in neovim to handle the horizontal scroll. Created issue neovim/neovim#3440

@rogual what do you think about a label that declares that an issue is a bug with neovim and not Neovim.app?

**Comment by rogual** [comment]
Good idea. Created the `upstream` label.

**Comment by bambu** [comment]
PR neovim/neovim#3450 was merged adding horizontal scrolling support. Horizontal scrolling in Neovim occurs the "natural" way if you do not have natural scrolling turned on. Created PR #251 to fix this

**Comment by bambu** [comment]
This can be closed as the fix has been merged
