### ISSUE TITLE
support opening files in the folder format

### ISSUE THREAD

**Issue by josephholsten** [rogual/neovim-dot-app#97]
I'm trying to open a folder, expecting the normal behaviour of a netrw listing. But when I run `open -a Neovim /tmp`, I get the following error:

![The document "tmp" could not be opened. Neovim cannot open files in the "folder" format.](https://dl.dropboxusercontent.com/u/447700/neo-folder.jpg)

**Comment by josephholsten** [comment]
ha, it doesn't even like opening my ~/.profile since it's in the "data" format.

**Comment by josephholsten** [comment]
![no idea](http://i1.kym-cdn.com/photos/images/newsfeed/000/234/765/b7e.jpg)

Looking at the current [res/Info.plist:CFBundleDocumentTypes](https://github.com/rogual/neovim-dot-app/blob/master/res/Info.plist#L33-L47) and it seems like there's a reanosable setting according to the doc in [Info Property List Key Reference > CoreFoundationKeys > CFBundleDocumentTypes](https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/TP40009249-101685-TPXREF107).

Checking the type of `/tmp`, I think we want to add `public.item` to the list:

    $ mdls -name kMDItemContentTypeTree /tmp
    kMDItemContentTypeTree = (
        "public.folder",
        "public.directory",
        "public.item"
    )

of course, `~/.profile` just thinks I look funny:

    $ mdls -name kMDItemContentTypeTree ~/.profile
    kMDItemContentTypeTree = (
    )
    $ mdls -name kMDItemContentType ~/.profile
    kMDItemContentType = "dyn.age8u"

**Comment by rogual** [comment]
Thanks for this! Should we add `public.item` to the list, rather than making it the only item in the list? Your PR removes the two existing items.

**Comment by josephholsten** [comment]
yeah, reviewing some blog posts, the other two should stay in.

Of course, I've discovered that you can't open a new (non-existant) file this way.  eg

```
$ open -a Neovim /tmp/nonexistant-new-file
The file /tmp/nonexistant-new-file does not exist.
```

Looking at the `mvim` helper script, it looks like they're essentially finding the path to the binary inside `Content/MacOS/` and `exec`ing to that (possibly with some added flags). This is equivalent to:

```
$ /usr/local/Cellar/neovim-dot-app/HEAD/Neovim.app/Contents/MacOS/Neovim /tmp/nonexistant-new-file
```

One important difference, MacVim somehow shuttles all these to the same open app, while doing this for Neovim causes me to have a new instance of the app for each call.

**Comment by rogual** [comment]
AFAIK you can never open a nonexistent file with `open` — the `open` command itself checks for the file and reports an error before your app is ever launched.

**Comment by rogual** [comment]
Merged that PR, let's see what happens.
