### ISSUE TITLE
Slow things

### ISSUE THREAD

**Issue by josephholsten** [rogual/neovim-dot-app#99]
I've noticed a number of things which feel slow. It probably makes sense to break these apart, but I don't know if & how they're related, so here's a list:
- scrolling (#75)
- window resize (both with mouse and through window managers like [spectacle](http://spectacleapp.com/))
- opening new tab (very slow)
- switching tabs
- rendering after opening new window

**Comment by rogual** [comment]
Optimizing redraws should be a priority to get these fixed.

**Comment by beaumartinez** [comment]
I noticed running commands in the command line (eg, `:help`) have slow output.

**Comment by bambu** [comment]
Looking at the redraw code. I  see that there are tons of try/catch's  in the  `case RedrawCode::highlight_set:`. There are many times where highlight_set message will have a null array. In that case there would be around 7 exceptions thrown. I changed the code to loop iterate through the array and the speed increased.  

The following is the result of timing the `RedrawCode::highlight_set` case when opening a new tab.

__Try/Catch:__
```
Elapsed time: 0.044
Elapsed time: 0.024
Elapsed time: 0.021
Elapsed time: 0.021
Elapsed time: 0.026
Elapsed time: 0.021
Elapsed time: 0.042
Elapsed time: 0.023
Elapsed time: 0.018
Elapsed time: 0.031
Elapsed time: 0.018
```

__Iterating:__
```
Elapsed time: 0.015
Elapsed time: 0.007
Elapsed time: 0.013
Elapsed time: 0.005
Elapsed time: 0.004
Elapsed time: 0.004
Elapsed time: 0.003
Elapsed time: 0.003
Elapsed time: 0.005
Elapsed time: 0.004
Elapsed time: 0.016
```

**Comment by rogual** [comment]
That's a big help, thanks @bambu. I've merged both those changes from that PR.

**Comment by philplckthun** [comment]
@josephholsten @beaumartinez Can you guys check out #109 and test if that makes a difference for you?
